import type { PlannedDigit } from '../engine/game';
import type { Cell, Dir } from '../engine/geometry';

/**
 * The fifteen fill puzzles: small boxes where filling every cell with noodle is the goal. Each
 * has a fixed sequence of digits, every one with its cell, so the same puzzle plays the same way
 * every time. They were designed by `scripts/design-puzzles.ts`, backwards from a route that
 * fills the box; `route` is the shortest way the solver found (U, D, L, R per move), and `par`
 * is its length. `puzzles.test.ts` replays every route and has the solver prove every puzzle
 * again on its own.
 */

export interface FillPuzzle {
  number: number;
  id: string;
  title: string;
  map: readonly string[];
  /** Head first. */
  start: readonly Cell[];
  heading: Dir;
  plan: readonly PlannedDigit[];
  par: number;
  route: string;
}

/** Moves allowed over par for the second star. */
export function secondStarMoves(puzzle: FillPuzzle): number {
  return puzzle.par + Math.max(4, Math.ceil(puzzle.par / 8));
}

export function routeDirs(route: string): Dir[] {
  const dirs: Record<string, Dir> = { U: 'up', D: 'down', L: 'left', R: 'right' };
  return [...route].map((ch) => dirs[ch]!);
}

export const PUZZLES: readonly FillPuzzle[] = [
  {
    number: 1,
    id: 'first-fill',
    title: 'First Fill',
    map: ['.....', '.....', '.....', '.....', '.....'],
    start: [
      { x: 0, y: 1 },
      { x: 1, y: 1 },
      { x: 2, y: 1 },
      { x: 2, y: 0 },
    ],
    heading: 'left',
    plan: [
      { value: 3, at: { x: 1, y: 0 } },
      { value: 4, at: { x: 2, y: 1 } },
      { value: 3, at: { x: 4, y: 0 } },
      { value: 3, at: { x: 3, y: 4 } },
      { value: 3, at: { x: 2, y: 2 } },
      { value: 5, at: { x: 0, y: 3 } },
    ],
    par: 23,
    route: 'URRDRURDDDDLUULLLDDRURD',
  },
  {
    number: 2,
    id: 'corner-shop',
    title: 'Corner Shop',
    map: ['......', '......', '......', '......', '......'],
    start: [
      { x: 4, y: 0 },
      { x: 5, y: 0 },
      { x: 5, y: 1 },
      { x: 5, y: 2 },
    ],
    heading: 'left',
    plan: [
      { value: 6, at: { x: 2, y: 0 } },
      { value: 6, at: { x: 2, y: 1 } },
      { value: 6, at: { x: 4, y: 2 } },
      { value: 5, at: { x: 0, y: 4 } },
      { value: 3, at: { x: 3, y: 3 } },
    ],
    par: 28,
    route: 'LLLLDRRRRRDLLLLLDDRURDRURRDL',
  },
  {
    number: 3,
    id: 'little-loop',
    title: 'Little Loop',
    map: ['......', '......', '..##..', '..##..', '......', '......'],
    start: [
      { x: 4, y: 2 },
      { x: 4, y: 3 },
      { x: 4, y: 4 },
      { x: 4, y: 5 },
      { x: 5, y: 5 },
    ],
    heading: 'up',
    plan: [
      { value: 6, at: { x: 5, y: 4 } },
      { value: 6, at: { x: 3, y: 5 } },
      { value: 2, at: { x: 0, y: 4 } },
      { value: 4, at: { x: 0, y: 3 } },
      { value: 3, at: { x: 1, y: 0 } },
      { value: 6, at: { x: 2, y: 0 } },
    ],
    par: 30,
    route: 'RDDDLULDLULDLUURULUURDRURDRURD',
  },
  {
    number: 4,
    id: 'the-hallway',
    title: 'The Hallway',
    map: ['........', '........', '........', '........', '........'],
    start: [
      { x: 4, y: 4 },
      { x: 4, y: 3 },
      { x: 4, y: 2 },
      { x: 4, y: 1 },
      { x: 4, y: 0 },
    ],
    heading: 'down',
    plan: [
      { value: 6, at: { x: 3, y: 3 } },
      { value: 7, at: { x: 2, y: 4 } },
      { value: 3, at: { x: 1, y: 0 } },
      { value: 5, at: { x: 1, y: 1 } },
      { value: 4, at: { x: 4, y: 0 } },
      { value: 7, at: { x: 5, y: 3 } },
      { value: 3, at: { x: 7, y: 1 } },
    ],
    par: 37,
    route: 'LUULDDLLURULUURDRURDRURDDDDRRULURUULD',
  },
  {
    number: 5,
    id: 'stepping-stones',
    title: 'Stepping Stones',
    map: ['.......', '..#....', '.......', '.......', '....#..', '.......'],
    start: [
      { x: 1, y: 5 },
      { x: 2, y: 5 },
      { x: 2, y: 4 },
      { x: 2, y: 3 },
      { x: 2, y: 2 },
    ],
    heading: 'left',
    plan: [
      { value: 3, at: { x: 0, y: 3 } },
      { value: 2, at: { x: 0, y: 2 } },
      { value: 2, at: { x: 0, y: 0 } },
      { value: 4, at: { x: 2, y: 0 } },
      { value: 5, at: { x: 6, y: 0 } },
      { value: 7, at: { x: 5, y: 2 } },
      { value: 6, at: { x: 3, y: 5 } },
      { value: 6, at: { x: 1, y: 3 } },
    ],
    par: 38,
    route: 'LUUUUURRRRRRDLDRDLDRDLLLULLURRRUULDLLU',
  },
  {
    number: 6,
    id: 'two-rooms',
    title: 'Two Rooms',
    map: ['....#...', '....#...', '........', '....#...', '....#...', '....#...'],
    start: [
      { x: 5, y: 5 },
      { x: 5, y: 4 },
      { x: 5, y: 3 },
      { x: 5, y: 2 },
      { x: 5, y: 1 },
    ],
    heading: 'down',
    plan: [
      { value: 6, at: { x: 7, y: 5 } },
      { value: 8, at: { x: 7, y: 3 } },
      { value: 3, at: { x: 5, y: 2 } },
      { value: 7, at: { x: 3, y: 0 } },
      { value: 6, at: { x: 1, y: 1 } },
      { value: 8, at: { x: 1, y: 5 } },
    ],
    par: 40,
    route: 'RRULURULURULLDDLLUULDDLUULDDDDDRUURRDDLU',
  },
  {
    number: 7,
    id: 'snail-shell',
    title: 'The Snail Shell',
    map: [
      '.........',
      '.........',
      '.........',
      '.........',
      '.........',
      '.........',
      '.........',
    ],
    start: [
      { x: 0, y: 0 },
      { x: 0, y: 1 },
      { x: 1, y: 1 },
      { x: 2, y: 1 },
      { x: 3, y: 1 },
      { x: 4, y: 1 },
    ],
    heading: 'up',
    plan: [
      { value: 6, at: { x: 5, y: 0 } },
      { value: 9, at: { x: 8, y: 2 } },
      { value: 9, at: { x: 4, y: 6 } },
      { value: 5, at: { x: 0, y: 1 } },
      { value: 9, at: { x: 6, y: 1 } },
      { value: 5, at: { x: 4, y: 5 } },
      { value: 6, at: { x: 1, y: 2 } },
      { value: 8, at: { x: 6, y: 4 } },
    ],
    par: 62,
    route: 'RRRRRRRRDDDDDDLLLLLLLLUUUUURRRRRRRDDDDLLLLLLUUURRRRRDDLULDLULD',
  },
  {
    number: 8,
    id: 'garden-ring',
    title: 'Garden Ring',
    map: [
      '........',
      '........',
      '........',
      '...##...',
      '...##...',
      '........',
      '........',
      '........',
    ],
    start: [
      { x: 2, y: 3 },
      { x: 2, y: 4 },
      { x: 1, y: 4 },
      { x: 1, y: 5 },
      { x: 2, y: 5 },
      { x: 3, y: 5 },
    ],
    heading: 'up',
    plan: [
      { value: 6, at: { x: 0, y: 4 } },
      { value: 5, at: { x: 4, y: 5 } },
      { value: 4, at: { x: 6, y: 5 } },
      { value: 4, at: { x: 3, y: 6 } },
      { value: 7, at: { x: 0, y: 6 } },
      { value: 7, at: { x: 6, y: 7 } },
      { value: 5, at: { x: 7, y: 0 } },
      { value: 9, at: { x: 3, y: 0 } },
      { value: 7, at: { x: 3, y: 2 } },
    ],
    par: 57,
    route: 'LLDDRRRRRUURDDDLLLLLLDRRRRRRRUUUUUUULLLLLLLDDRURDRURDRURD',
  },
  {
    number: 9,
    id: 'zigzag',
    title: 'Zigzag',
    map: [
      '..#......',
      '..#......',
      '..#......',
      '.........',
      '.........',
      '......#..',
      '......#..',
      '......#..',
    ],
    start: [
      { x: 5, y: 0 },
      { x: 4, y: 0 },
      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 4, y: 1 },
      { x: 5, y: 1 },
    ],
    heading: 'right',
    plan: [
      { value: 5, at: { x: 8, y: 0 } },
      { value: 4, at: { x: 8, y: 3 } },
      { value: 3, at: { x: 7, y: 6 } },
      { value: 4, at: { x: 7, y: 5 } },
      { value: 7, at: { x: 6, y: 1 } },
      { value: 7, at: { x: 6, y: 3 } },
      { value: 8, at: { x: 3, y: 3 } },
      { value: 6, at: { x: 0, y: 4 } },
      { value: 7, at: { x: 4, y: 5 } },
      { value: 9, at: { x: 3, y: 6 } },
    ],
    par: 63,
    route: 'RRRDDDDDDDLUUUUUULDDDLUUULLDRDLLLUUULDDDDRRRRDRDDLULULDLULDDRRR',
  },
  {
    number: 10,
    id: 'the-comb',
    title: 'The Comb',
    map: [
      '..#..#..#.',
      '..#..#..#.',
      '..#..#..#.',
      '..........',
      '..........',
      '..........',
      '..........',
    ],
    start: [
      { x: 1, y: 2 },
      { x: 1, y: 3 },
      { x: 2, y: 3 },
      { x: 3, y: 3 },
      { x: 3, y: 2 },
      { x: 3, y: 1 },
    ],
    heading: 'up',
    plan: [
      { value: 9, at: { x: 0, y: 0 } },
      { value: 6, at: { x: 1, y: 4 } },
      { value: 5, at: { x: 3, y: 6 } },
      { value: 8, at: { x: 9, y: 5 } },
      { value: 6, at: { x: 6, y: 5 } },
      { value: 4, at: { x: 3, y: 5 } },
      { value: 9, at: { x: 4, y: 0 } },
      { value: 8, at: { x: 6, y: 1 } },
    ],
    par: 58,
    route: 'UULDDDDRRDLLDRRRRRRRRRULLULDLLLUUUUURDDDDRURUUURDDDRDRUUUU',
  },
  {
    number: 11,
    id: 'courtyard',
    title: 'Courtyard',
    map: [
      '#........#',
      '..........',
      '..........',
      '....##....',
      '....##....',
      '..........',
      '..........',
      '..........',
    ],
    start: [
      { x: 2, y: 0 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 2, y: 1 },
      { x: 3, y: 1 },
      { x: 4, y: 1 },
    ],
    heading: 'right',
    plan: [
      { value: 8, at: { x: 6, y: 0 } },
      { value: 5, at: { x: 9, y: 5 } },
      { value: 5, at: { x: 6, y: 7 } },
      { value: 7, at: { x: 1, y: 7 } },
      { value: 7, at: { x: 4, y: 5 } },
      { value: 8, at: { x: 2, y: 5 } },
      { value: 4, at: { x: 0, y: 1 } },
      { value: 4, at: { x: 2, y: 1 } },
      { value: 8, at: { x: 4, y: 1 } },
      { value: 5, at: { x: 8, y: 3 } },
      { value: 7, at: { x: 7, y: 6 } },
    ],
    par: 72,
    route: 'RRRRRRDRDDDDDDLLLLLLLLLURRRRULLLLUUUURDDDRRULUURDRURDRURDRDDDDLUUULDDDLU',
  },
  {
    number: 12,
    id: 'long-table',
    title: 'Long Table',
    map: [
      '...........',
      '...........',
      '...........',
      '..#######..',
      '...........',
      '...........',
      '...........',
      '...........',
    ],
    start: [
      { x: 6, y: 2 },
      { x: 5, y: 2 },
      { x: 5, y: 1 },
      { x: 5, y: 0 },
      { x: 6, y: 0 },
      { x: 7, y: 0 },
      { x: 8, y: 0 },
    ],
    heading: 'right',
    plan: [
      { value: 4, at: { x: 10, y: 2 } },
      { value: 7, at: { x: 10, y: 0 } },
      { value: 4, at: { x: 5, y: 0 } },
      { value: 9, at: { x: 3, y: 2 } },
      { value: 9, at: { x: 2, y: 1 } },
      { value: 8, at: { x: 1, y: 5 } },
      { value: 7, at: { x: 3, y: 4 } },
      { value: 5, at: { x: 8, y: 4 } },
      { value: 9, at: { x: 4, y: 5 } },
      { value: 8, at: { x: 7, y: 7 } },
      { value: 4, at: { x: 10, y: 6 } },
    ],
    par: 78,
    route: 'RRRRUULDLULDLULLDDLUULDDLUULDDDRDLDRRURRRRRRDLLLLLDLLLDRRRRURDRURDRURDRUULUURD',
  },
  {
    number: 13,
    id: 'crossroads',
    title: 'Crossroads',
    map: [
      '...........',
      '...........',
      '..##...##..',
      '..##...##..',
      '...........',
      '..##...##..',
      '..##...##..',
      '...........',
      '...........',
    ],
    start: [
      { x: 0, y: 2 },
      { x: 0, y: 1 },
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: 2, y: 0 },
      { x: 3, y: 0 },
      { x: 4, y: 0 },
    ],
    heading: 'down',
    plan: [
      { value: 8, at: { x: 0, y: 6 } },
      { value: 6, at: { x: 1, y: 7 } },
      { value: 7, at: { x: 2, y: 4 } },
      { value: 5, at: { x: 6, y: 3 } },
      { value: 7, at: { x: 9, y: 4 } },
      { value: 7, at: { x: 6, y: 6 } },
      { value: 7, at: { x: 4, y: 7 } },
      { value: 8, at: { x: 10, y: 8 } },
      { value: 8, at: { x: 9, y: 2 } },
      { value: 5, at: { x: 7, y: 1 } },
      { value: 8, at: { x: 4, y: 0 } },
    ],
    par: 80,
    route: 'DDDDDDRUUUURRRUURRDLDRRRRDDDLLLUULLDRDLLLDRRRRRRRRUUUUULURUULDLULDLULDLULDLULDDD',
  },
  {
    number: 14,
    id: 'terraces',
    title: 'Terraces',
    map: [
      '...#.....#..',
      '...#.....#..',
      '...#.....#..',
      '...#.....#..',
      '......#.....',
      '......#.....',
      '......#.....',
      '......#.....',
    ],
    start: [
      { x: 0, y: 1 },
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: 2, y: 0 },
      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 2, y: 3 },
    ],
    heading: 'down',
    plan: [
      { value: 9, at: { x: 0, y: 6 } },
      { value: 7, at: { x: 1, y: 1 } },
      { value: 8, at: { x: 3, y: 5 } },
      { value: 7, at: { x: 4, y: 6 } },
      { value: 5, at: { x: 4, y: 3 } },
      { value: 9, at: { x: 4, y: 1 } },
      { value: 6, at: { x: 6, y: 2 } },
      { value: 7, at: { x: 7, y: 4 } },
      { value: 8, at: { x: 7, y: 7 } },
      { value: 6, at: { x: 10, y: 1 } },
      { value: 5, at: { x: 11, y: 5 } },
    ],
    par: 82,
    route: 'DDDDDDRUUUUUUURDDDDRDLDDRURDRUULURULUUURRRRDLLLDRDRURDDLDDDRUURURUUUURDDDDDLDRDLLU',
  },
  {
    number: 15,
    id: 'the-big-box',
    title: 'The Big Box',
    map: [
      '............',
      '............',
      '............',
      '............',
      '............',
      '............',
      '............',
      '............',
      '............',
    ],
    start: [
      { x: 6, y: 8 },
      { x: 7, y: 8 },
      { x: 8, y: 8 },
      { x: 8, y: 7 },
      { x: 8, y: 6 },
      { x: 8, y: 5 },
      { x: 8, y: 4 },
      { x: 8, y: 3 },
    ],
    heading: 'left',
    plan: [
      { value: 5, at: { x: 1, y: 8 } },
      { value: 5, at: { x: 2, y: 7 } },
      { value: 6, at: { x: 7, y: 7 } },
      { value: 7, at: { x: 5, y: 6 } },
      { value: 8, at: { x: 3, y: 5 } },
      { value: 9, at: { x: 9, y: 5 } },
      { value: 5, at: { x: 11, y: 6 } },
      { value: 7, at: { x: 11, y: 1 } },
      { value: 9, at: { x: 10, y: 3 } },
      { value: 5, at: { x: 0, y: 4 } },
      { value: 6, at: { x: 1, y: 0 } },
      { value: 8, at: { x: 5, y: 0 } },
      { value: 6, at: { x: 7, y: 1 } },
      { value: 7, at: { x: 1, y: 1 } },
      { value: 7, at: { x: 3, y: 3 } },
    ],
    par: 105,
    route:
      'LLLLLLURRRRRRRRULLLLLLLLURRRRRRRRRDDDRRULURULURUUUULDDDLDLLLLLLLLLUUUURRRRRRRRRDDLULLLLLLLDDRURDRURDRURDR',
  },
];
