import type { Arena } from '../engine/arena';

/**
 * The fifteen arenas of the 1986 game, in the order of its game list, under names of our own.
 * Sizes, update intervals, arrival odds, gates, beacons, runways and airway lines are taken from
 * the original arena files (converted once by a script outside the repository); the scenery is
 * Skyloom's decoration.
 *
 * Derived from atc by Ed James, UC Berkeley:
 *   Copyright (c) 1990, 1993 The Regents of the University of California. All rights reserved.
 *   Copyright (c) 1987 by Ed James, UC Berkeley. All rights reserved.
 * Used under the BSD licence (LICENSES/BSD-3-Clause-UCB.txt) and Ed James's notice
 * (LICENSES/atc-Ed-James.txt); see CREDITS.md.
 */
export interface ClassicArena extends Arena {
  /** Position in the original game list, 1–15. */
  classic: number;
}

export const CLASSIC_ARENAS: readonly ClassicArena[] = [
  {
    id: 'old-reliable',
    name: 'Old Reliable',
    classic: 1,
    width: 30,
    height: 21,
    tickSeconds: 5,
    spawnOneIn: 10,
    gates: [
      { x: 12, y: 0, heading: 4 },
      { x: 29, y: 0, heading: 5 },
      { x: 29, y: 7, heading: 6 },
      { x: 29, y: 17, heading: 6 },
      { x: 9, y: 20, heading: 1 },
      { x: 0, y: 13, heading: 2 },
      { x: 0, y: 7, heading: 2 },
      { x: 0, y: 0, heading: 3 },
    ],
    beacons: [
      { x: 12, y: 7 },
      { x: 12, y: 17 },
    ],
    runways: [
      { x: 20, y: 15, heading: 0 },
      { x: 20, y: 18, heading: 2 },
    ],
    airways: [
      { from: { x: 1, y: 1 }, to: { x: 6, y: 6 } },
      { from: { x: 12, y: 1 }, to: { x: 12, y: 6 } },
      { from: { x: 13, y: 7 }, to: { x: 28, y: 7 } },
      { from: { x: 28, y: 1 }, to: { x: 13, y: 16 } },
      { from: { x: 1, y: 13 }, to: { x: 11, y: 13 } },
      { from: { x: 12, y: 8 }, to: { x: 12, y: 16 } },
      { from: { x: 11, y: 18 }, to: { x: 10, y: 19 } },
      { from: { x: 13, y: 17 }, to: { x: 28, y: 17 } },
      { from: { x: 1, y: 7 }, to: { x: 11, y: 7 } },
    ],
    scenery: { seed: 'old-reliable', relief: 0.5 },
  },
  {
    id: 'little-field',
    name: 'Little Field',
    classic: 2,
    width: 15,
    height: 15,
    tickSeconds: 7,
    spawnOneIn: 12,
    gates: [
      { x: 7, y: 0, heading: 4 },
      { x: 14, y: 0, heading: 5 },
      { x: 12, y: 14, heading: 7 },
      { x: 0, y: 14, heading: 1 },
    ],
    beacons: [{ x: 12, y: 7 }],
    runways: [{ x: 7, y: 8, heading: 0 }],
    airways: [
      { from: { x: 1, y: 1 }, to: { x: 6, y: 6 } },
      { from: { x: 7, y: 9 }, to: { x: 12, y: 14 } },
      { from: { x: 7, y: 0 }, to: { x: 7, y: 14 } },
      { from: { x: 1, y: 7 }, to: { x: 11, y: 7 } },
    ],
    scenery: { seed: 'little-field', relief: 0.3 },
  },
  {
    id: 'saltire',
    name: 'Saltire',
    classic: 3,
    width: 29,
    height: 21,
    tickSeconds: 5,
    spawnOneIn: 5,
    gates: [
      { x: 0, y: 0, heading: 3 },
      { x: 8, y: 0, heading: 3 },
      { x: 20, y: 0, heading: 5 },
      { x: 28, y: 0, heading: 5 },
      { x: 28, y: 20, heading: 7 },
      { x: 20, y: 20, heading: 7 },
      { x: 8, y: 20, heading: 1 },
      { x: 0, y: 20, heading: 1 },
    ],
    beacons: [
      { x: 14, y: 6 },
      { x: 18, y: 10 },
      { x: 14, y: 14 },
      { x: 10, y: 10 },
    ],
    runways: [],
    airways: [
      { from: { x: 0, y: 0 }, to: { x: 20, y: 20 } },
      { from: { x: 8, y: 0 }, to: { x: 28, y: 20 } },
      { from: { x: 20, y: 0 }, to: { x: 0, y: 20 } },
      { from: { x: 28, y: 0 }, to: { x: 8, y: 20 } },
    ],
    scenery: { seed: 'saltire', coast: 'south', relief: 0.4 },
  },
  {
    id: 'overdrive',
    name: 'Overdrive',
    classic: 4,
    width: 30,
    height: 21,
    tickSeconds: 1,
    spawnOneIn: 4,
    gates: [
      { x: 29, y: 7, heading: 6 },
      { x: 29, y: 17, heading: 6 },
      { x: 0, y: 7, heading: 2 },
      { x: 0, y: 0, heading: 3 },
    ],
    beacons: [
      { x: 12, y: 7 },
      { x: 12, y: 17 },
      { x: 14, y: 10 },
      { x: 20, y: 15 },
    ],
    runways: [{ x: 20, y: 18, heading: 2 }],
    airways: [
      { from: { x: 1, y: 1 }, to: { x: 6, y: 6 } },
      { from: { x: 12, y: 1 }, to: { x: 12, y: 6 } },
      { from: { x: 13, y: 7 }, to: { x: 28, y: 7 } },
      { from: { x: 28, y: 1 }, to: { x: 13, y: 16 } },
      { from: { x: 1, y: 13 }, to: { x: 11, y: 13 } },
      { from: { x: 12, y: 8 }, to: { x: 12, y: 16 } },
      { from: { x: 11, y: 18 }, to: { x: 10, y: 19 } },
      { from: { x: 13, y: 17 }, to: { x: 28, y: 17 } },
      { from: { x: 1, y: 7 }, to: { x: 11, y: 7 } },
    ],
    scenery: { seed: 'overdrive', relief: 0.85 },
  },
  {
    id: 'seven-beacons',
    name: 'Seven Beacons',
    classic: 5,
    width: 30,
    height: 21,
    tickSeconds: 5,
    spawnOneIn: 8,
    gates: [
      { x: 12, y: 0, heading: 4 },
      { x: 29, y: 0, heading: 5 },
      { x: 29, y: 6, heading: 6 },
      { x: 29, y: 13, heading: 6 },
      { x: 9, y: 20, heading: 1 },
      { x: 0, y: 13, heading: 2 },
      { x: 0, y: 6, heading: 2 },
      { x: 0, y: 0, heading: 3 },
    ],
    beacons: [
      { x: 12, y: 17 },
      { x: 23, y: 6 },
      { x: 23, y: 13 },
      { x: 25, y: 17 },
      { x: 12, y: 6 },
      { x: 12, y: 13 },
      { x: 6, y: 6 },
    ],
    runways: [{ x: 18, y: 17, heading: 2 }],
    airways: [
      { from: { x: 1, y: 1 }, to: { x: 16, y: 16 } },
      { from: { x: 1, y: 6 }, to: { x: 28, y: 6 } },
      { from: { x: 12, y: 1 }, to: { x: 12, y: 17 } },
      { from: { x: 10, y: 19 }, to: { x: 28, y: 1 } },
      { from: { x: 13, y: 17 }, to: { x: 17, y: 17 } },
      { from: { x: 1, y: 13 }, to: { x: 28, y: 13 } },
      { from: { x: 19, y: 17 }, to: { x: 24, y: 17 } },
      { from: { x: 19, y: 17 }, to: { x: 22, y: 14 } },
      { from: { x: 26, y: 16 }, to: { x: 28, y: 14 } },
    ],
    scenery: { seed: 'seven-beacons', coast: 'north', relief: 0.5 },
  },
  {
    id: 'deep-lanes',
    name: 'Deep Lanes',
    classic: 6,
    width: 30,
    height: 21,
    tickSeconds: 5,
    spawnOneIn: 5,
    gates: [
      { x: 10, y: 0, heading: 4 },
      { x: 29, y: 6, heading: 6 },
      { x: 27, y: 20, heading: 7 },
      { x: 0, y: 16, heading: 2 },
    ],
    beacons: [
      { x: 10, y: 6 },
      { x: 23, y: 6 },
      { x: 23, y: 16 },
      { x: 15, y: 16 },
      { x: 7, y: 16 },
      { x: 7, y: 9 },
      { x: 15, y: 6 },
    ],
    runways: [
      { x: 23, y: 8, heading: 4 },
      { x: 15, y: 12, heading: 0 },
    ],
    airways: [
      { from: { x: 10, y: 1 }, to: { x: 10, y: 5 } },
      { from: { x: 11, y: 6 }, to: { x: 14, y: 6 } },
      { from: { x: 16, y: 6 }, to: { x: 22, y: 6 } },
      { from: { x: 24, y: 6 }, to: { x: 28, y: 6 } },
      { from: { x: 1, y: 16 }, to: { x: 6, y: 16 } },
      { from: { x: 8, y: 16 }, to: { x: 14, y: 16 } },
      { from: { x: 16, y: 16 }, to: { x: 22, y: 16 } },
      { from: { x: 23, y: 7 }, to: { x: 23, y: 7 } },
      { from: { x: 23, y: 9 }, to: { x: 23, y: 15 } },
      { from: { x: 15, y: 7 }, to: { x: 15, y: 11 } },
      { from: { x: 15, y: 13 }, to: { x: 15, y: 15 } },
      { from: { x: 7, y: 10 }, to: { x: 7, y: 15 } },
      { from: { x: 9, y: 7 }, to: { x: 8, y: 8 } },
      { from: { x: 6, y: 10 }, to: { x: 1, y: 15 } },
      { from: { x: 24, y: 17 }, to: { x: 26, y: 19 } },
    ],
    scenery: { seed: 'deep-lanes', coast: 'west', relief: 0.45 },
  },
  {
    id: 'lakeside-hub',
    name: 'Lakeside Hub',
    classic: 7,
    width: 30,
    height: 21,
    tickSeconds: 5,
    spawnOneIn: 5,
    gates: [
      { x: 6, y: 0, heading: 4 },
      { x: 18, y: 0, heading: 4 },
      { x: 29, y: 5, heading: 6 },
      { x: 29, y: 13, heading: 6 },
      { x: 14, y: 20, heading: 1 },
      { x: 6, y: 20, heading: 0 },
    ],
    beacons: [
      { x: 6, y: 5 },
      { x: 18, y: 5 },
      { x: 6, y: 13 },
    ],
    runways: [{ x: 8, y: 8, heading: 2 }],
    airways: [
      { from: { x: 6, y: 1 }, to: { x: 6, y: 4 } },
      { from: { x: 18, y: 1 }, to: { x: 18, y: 4 } },
      { from: { x: 6, y: 6 }, to: { x: 6, y: 12 } },
      { from: { x: 6, y: 14 }, to: { x: 6, y: 19 } },
      { from: { x: 28, y: 6 }, to: { x: 15, y: 19 } },
      { from: { x: 7, y: 13 }, to: { x: 20, y: 13 } },
      { from: { x: 22, y: 13 }, to: { x: 28, y: 13 } },
      { from: { x: 7, y: 5 }, to: { x: 17, y: 5 } },
      { from: { x: 19, y: 5 }, to: { x: 28, y: 5 } },
    ],
    scenery: { seed: 'lakeside-hub', coast: 'east', relief: 0.25 },
  },
  {
    id: 'noughts',
    name: 'Noughts',
    classic: 8,
    width: 30,
    height: 21,
    tickSeconds: 5,
    spawnOneIn: 5,
    gates: [
      { x: 10, y: 0, heading: 4 },
      { x: 19, y: 0, heading: 4 },
      { x: 29, y: 7, heading: 6 },
      { x: 29, y: 13, heading: 6 },
      { x: 19, y: 20, heading: 0 },
      { x: 10, y: 20, heading: 0 },
      { x: 0, y: 13, heading: 2 },
      { x: 0, y: 7, heading: 2 },
    ],
    beacons: [
      { x: 10, y: 7 },
      { x: 19, y: 7 },
      { x: 19, y: 13 },
      { x: 10, y: 13 },
    ],
    runways: [],
    airways: [
      { from: { x: 10, y: 1 }, to: { x: 10, y: 6 } },
      { from: { x: 19, y: 1 }, to: { x: 19, y: 6 } },
      { from: { x: 1, y: 7 }, to: { x: 9, y: 7 } },
      { from: { x: 11, y: 7 }, to: { x: 18, y: 7 } },
      { from: { x: 20, y: 7 }, to: { x: 28, y: 7 } },
      { from: { x: 10, y: 8 }, to: { x: 10, y: 12 } },
      { from: { x: 19, y: 8 }, to: { x: 19, y: 12 } },
      { from: { x: 1, y: 13 }, to: { x: 9, y: 13 } },
      { from: { x: 11, y: 13 }, to: { x: 18, y: 13 } },
      { from: { x: 20, y: 13 }, to: { x: 28, y: 13 } },
      { from: { x: 10, y: 14 }, to: { x: 10, y: 19 } },
      { from: { x: 19, y: 14 }, to: { x: 19, y: 19 } },
    ],
    scenery: { seed: 'noughts', relief: 0.35 },
  },
  {
    id: 'seven-fields',
    name: 'Seven Fields',
    classic: 9,
    width: 30,
    height: 21,
    tickSeconds: 6,
    spawnOneIn: 6,
    gates: [
      { x: 13, y: 0, heading: 4 },
      { x: 0, y: 10, heading: 2 },
    ],
    beacons: [
      { x: 6, y: 3 },
      { x: 19, y: 4 },
      { x: 27, y: 4 },
      { x: 27, y: 10 },
      { x: 27, y: 16 },
      { x: 13, y: 16 },
      { x: 6, y: 16 },
      { x: 13, y: 10 },
      { x: 19, y: 10 },
    ],
    runways: [
      { x: 6, y: 5, heading: 0 },
      { x: 23, y: 4, heading: 6 },
      { x: 19, y: 7, heading: 0 },
      { x: 25, y: 10, heading: 2 },
      { x: 24, y: 16, heading: 6 },
      { x: 13, y: 13, heading: 4 },
      { x: 6, y: 13, heading: 0 },
    ],
    airways: [
      { from: { x: 13, y: 1 }, to: { x: 13, y: 9 } },
      { from: { x: 13, y: 11 }, to: { x: 13, y: 12 } },
      { from: { x: 13, y: 14 }, to: { x: 13, y: 15 } },
      { from: { x: 7, y: 16 }, to: { x: 12, y: 16 } },
      { from: { x: 18, y: 5 }, to: { x: 14, y: 9 } },
      { from: { x: 6, y: 14 }, to: { x: 6, y: 15 } },
      { from: { x: 6, y: 11 }, to: { x: 6, y: 12 } },
      { from: { x: 6, y: 6 }, to: { x: 6, y: 9 } },
      { from: { x: 1, y: 10 }, to: { x: 12, y: 10 } },
      { from: { x: 27, y: 5 }, to: { x: 27, y: 9 } },
      { from: { x: 27, y: 11 }, to: { x: 27, y: 15 } },
    ],
    scenery: { seed: 'seven-fields', relief: 0.3 },
  },
  {
    id: 'square-dance',
    name: 'Square Dance',
    classic: 10,
    width: 29,
    height: 21,
    tickSeconds: 5,
    spawnOneIn: 6,
    gates: [
      { x: 0, y: 0, heading: 3 },
      { x: 14, y: 0, heading: 4 },
      { x: 28, y: 0, heading: 5 },
      { x: 28, y: 10, heading: 6 },
      { x: 28, y: 20, heading: 7 },
      { x: 14, y: 20, heading: 0 },
      { x: 0, y: 20, heading: 1 },
      { x: 0, y: 10, heading: 2 },
    ],
    beacons: [
      { x: 4, y: 4 },
      { x: 14, y: 4 },
      { x: 24, y: 4 },
      { x: 24, y: 10 },
      { x: 24, y: 16 },
      { x: 14, y: 16 },
      { x: 4, y: 16 },
      { x: 4, y: 10 },
      { x: 14, y: 13 },
      { x: 14, y: 7 },
    ],
    runways: [
      { x: 9, y: 7, heading: 6 },
      { x: 19, y: 7, heading: 2 },
      { x: 19, y: 13, heading: 2 },
      { x: 9, y: 13, heading: 6 },
    ],
    airways: [
      { from: { x: 1, y: 1 }, to: { x: 3, y: 3 } },
      { from: { x: 14, y: 1 }, to: { x: 14, y: 3 } },
      { from: { x: 27, y: 1 }, to: { x: 25, y: 3 } },
      { from: { x: 5, y: 4 }, to: { x: 13, y: 4 } },
      { from: { x: 15, y: 4 }, to: { x: 23, y: 4 } },
      { from: { x: 4, y: 5 }, to: { x: 4, y: 9 } },
      { from: { x: 14, y: 5 }, to: { x: 14, y: 6 } },
      { from: { x: 24, y: 5 }, to: { x: 24, y: 9 } },
      { from: { x: 10, y: 7 }, to: { x: 13, y: 7 } },
      { from: { x: 15, y: 7 }, to: { x: 18, y: 7 } },
      { from: { x: 14, y: 8 }, to: { x: 14, y: 9 } },
      { from: { x: 1, y: 10 }, to: { x: 3, y: 10 } },
      { from: { x: 5, y: 10 }, to: { x: 23, y: 10 } },
      { from: { x: 25, y: 10 }, to: { x: 27, y: 10 } },
      { from: { x: 4, y: 11 }, to: { x: 4, y: 15 } },
      { from: { x: 14, y: 11 }, to: { x: 14, y: 12 } },
      { from: { x: 24, y: 11 }, to: { x: 24, y: 15 } },
      { from: { x: 10, y: 13 }, to: { x: 13, y: 13 } },
      { from: { x: 15, y: 13 }, to: { x: 18, y: 13 } },
      { from: { x: 14, y: 14 }, to: { x: 14, y: 15 } },
      { from: { x: 5, y: 16 }, to: { x: 13, y: 16 } },
      { from: { x: 15, y: 16 }, to: { x: 23, y: 16 } },
      { from: { x: 3, y: 17 }, to: { x: 1, y: 19 } },
      { from: { x: 14, y: 17 }, to: { x: 14, y: 19 } },
      { from: { x: 25, y: 17 }, to: { x: 27, y: 19 } },
    ],
    scenery: { seed: 'square-dance', relief: 0.55 },
  },
  {
    id: 'hatchwork',
    name: 'Hatchwork',
    classic: 11,
    width: 30,
    height: 21,
    tickSeconds: 5,
    spawnOneIn: 5,
    gates: [
      { x: 0, y: 10, heading: 2 },
      { x: 6, y: 0, heading: 4 },
      { x: 12, y: 0, heading: 4 },
      { x: 18, y: 0, heading: 4 },
      { x: 24, y: 0, heading: 4 },
      { x: 29, y: 10, heading: 6 },
      { x: 24, y: 20, heading: 0 },
      { x: 18, y: 20, heading: 0 },
      { x: 12, y: 20, heading: 0 },
      { x: 6, y: 20, heading: 0 },
    ],
    beacons: [
      { x: 6, y: 10 },
      { x: 12, y: 10 },
      { x: 18, y: 10 },
      { x: 24, y: 10 },
      { x: 6, y: 5 },
      { x: 12, y: 5 },
      { x: 18, y: 5 },
      { x: 24, y: 5 },
      { x: 12, y: 15 },
      { x: 18, y: 15 },
    ],
    runways: [
      { x: 9, y: 15, heading: 6 },
      { x: 21, y: 15, heading: 2 },
      { x: 15, y: 5, heading: 2 },
    ],
    airways: [
      { from: { x: 6, y: 1 }, to: { x: 6, y: 4 } },
      { from: { x: 12, y: 1 }, to: { x: 12, y: 4 } },
      { from: { x: 18, y: 1 }, to: { x: 18, y: 4 } },
      { from: { x: 24, y: 1 }, to: { x: 24, y: 4 } },
      { from: { x: 6, y: 6 }, to: { x: 6, y: 9 } },
      { from: { x: 12, y: 6 }, to: { x: 12, y: 9 } },
      { from: { x: 18, y: 6 }, to: { x: 18, y: 9 } },
      { from: { x: 24, y: 6 }, to: { x: 24, y: 9 } },
      { from: { x: 12, y: 11 }, to: { x: 12, y: 14 } },
      { from: { x: 18, y: 11 }, to: { x: 18, y: 14 } },
      { from: { x: 6, y: 11 }, to: { x: 6, y: 19 } },
      { from: { x: 24, y: 11 }, to: { x: 24, y: 19 } },
      { from: { x: 12, y: 16 }, to: { x: 12, y: 19 } },
      { from: { x: 18, y: 16 }, to: { x: 18, y: 19 } },
      { from: { x: 7, y: 5 }, to: { x: 11, y: 5 } },
      { from: { x: 19, y: 5 }, to: { x: 23, y: 5 } },
      { from: { x: 13, y: 15 }, to: { x: 17, y: 15 } },
      { from: { x: 1, y: 10 }, to: { x: 5, y: 10 } },
      { from: { x: 7, y: 10 }, to: { x: 11, y: 10 } },
      { from: { x: 13, y: 10 }, to: { x: 17, y: 10 } },
      { from: { x: 19, y: 10 }, to: { x: 23, y: 10 } },
      { from: { x: 25, y: 10 }, to: { x: 29, y: 10 } },
    ],
    scenery: { seed: 'hatchwork', coast: 'south', relief: 0.6 },
  },
  {
    id: 'lone-beacon',
    name: 'Lone Beacon',
    classic: 12,
    width: 30,
    height: 21,
    tickSeconds: 5,
    spawnOneIn: 5,
    gates: [
      { x: 12, y: 0, heading: 4 },
      { x: 0, y: 6, heading: 2 },
      { x: 29, y: 12, heading: 6 },
      { x: 26, y: 20, heading: 7 },
    ],
    beacons: [{ x: 12, y: 6 }],
    runways: [{ x: 8, y: 11, heading: 4 }],
    airways: [
      { from: { x: 12, y: 1 }, to: { x: 12, y: 5 } },
      { from: { x: 1, y: 6 }, to: { x: 11, y: 6 } },
      { from: { x: 8, y: 7 }, to: { x: 8, y: 10 } },
      { from: { x: 28, y: 12 }, to: { x: 19, y: 12 } },
      { from: { x: 13, y: 7 }, to: { x: 25, y: 19 } },
    ],
    scenery: { seed: 'lone-beacon', coast: 'east', relief: 0.7 },
  },
  {
    id: 'ten-beacons',
    name: 'Ten Beacons',
    classic: 13,
    width: 30,
    height: 21,
    tickSeconds: 5,
    spawnOneIn: 5,
    gates: [
      { x: 9, y: 0, heading: 3 },
      { x: 29, y: 0, heading: 5 },
      { x: 29, y: 20, heading: 7 },
      { x: 9, y: 20, heading: 1 },
      { x: 0, y: 20, heading: 1 },
      { x: 0, y: 10, heading: 2 },
      { x: 0, y: 0, heading: 3 },
    ],
    beacons: [
      { x: 5, y: 5 },
      { x: 14, y: 5 },
      { x: 24, y: 5 },
      { x: 24, y: 9 },
      { x: 24, y: 11 },
      { x: 24, y: 15 },
      { x: 14, y: 15 },
      { x: 5, y: 15 },
      { x: 5, y: 10 },
      { x: 14, y: 10 },
    ],
    runways: [
      { x: 19, y: 9, heading: 6 },
      { x: 19, y: 11, heading: 6 },
    ],
    airways: [
      { from: { x: 1, y: 1 }, to: { x: 4, y: 4 } },
      { from: { x: 10, y: 1 }, to: { x: 13, y: 4 } },
      { from: { x: 28, y: 1 }, to: { x: 25, y: 4 } },
      { from: { x: 6, y: 5 }, to: { x: 13, y: 5 } },
      { from: { x: 15, y: 5 }, to: { x: 23, y: 5 } },
      { from: { x: 1, y: 10 }, to: { x: 13, y: 10 } },
      { from: { x: 15, y: 10 }, to: { x: 17, y: 10 } },
      { from: { x: 18, y: 9 }, to: { x: 18, y: 9 } },
      { from: { x: 18, y: 11 }, to: { x: 18, y: 11 } },
      { from: { x: 20, y: 9 }, to: { x: 23, y: 9 } },
      { from: { x: 20, y: 11 }, to: { x: 23, y: 11 } },
      { from: { x: 6, y: 15 }, to: { x: 13, y: 15 } },
      { from: { x: 15, y: 15 }, to: { x: 24, y: 15 } },
      { from: { x: 1, y: 19 }, to: { x: 4, y: 16 } },
      { from: { x: 10, y: 19 }, to: { x: 13, y: 16 } },
      { from: { x: 28, y: 19 }, to: { x: 25, y: 16 } },
      { from: { x: 5, y: 6 }, to: { x: 5, y: 9 } },
      { from: { x: 5, y: 11 }, to: { x: 5, y: 14 } },
      { from: { x: 14, y: 6 }, to: { x: 14, y: 9 } },
      { from: { x: 14, y: 11 }, to: { x: 14, y: 14 } },
      { from: { x: 24, y: 6 }, to: { x: 24, y: 8 } },
      { from: { x: 24, y: 10 }, to: { x: 24, y: 10 } },
      { from: { x: 24, y: 12 }, to: { x: 24, y: 14 } },
    ],
    scenery: { seed: 'ten-beacons', relief: 0.45 },
  },
  {
    id: 'training-ground',
    name: 'Training Ground',
    classic: 14,
    width: 30,
    height: 21,
    tickSeconds: 6,
    spawnOneIn: 6,
    gates: [
      { x: 0, y: 2, heading: 3 },
      { x: 29, y: 2, heading: 5 },
      { x: 29, y: 18, heading: 7 },
      { x: 0, y: 18, heading: 1 },
    ],
    beacons: [
      { x: 8, y: 10 },
      { x: 21, y: 10 },
    ],
    runways: [],
    airways: [
      { from: { x: 1, y: 3 }, to: { x: 7, y: 9 } },
      { from: { x: 7, y: 11 }, to: { x: 1, y: 17 } },
      { from: { x: 28, y: 3 }, to: { x: 22, y: 9 } },
      { from: { x: 22, y: 11 }, to: { x: 28, y: 17 } },
      { from: { x: 9, y: 10 }, to: { x: 20, y: 10 } },
    ],
    scenery: { seed: 'training-ground', relief: 0.2 },
  },
  {
    id: 'corner-pockets',
    name: 'Corner Pockets',
    classic: 15,
    width: 30,
    height: 21,
    tickSeconds: 5,
    spawnOneIn: 5,
    gates: [
      { x: 0, y: 0, heading: 3 },
      { x: 10, y: 0, heading: 4 },
      { x: 29, y: 10, heading: 6 },
      { x: 29, y: 20, heading: 7 },
      { x: 19, y: 20, heading: 0 },
      { x: 0, y: 10, heading: 2 },
    ],
    beacons: [
      { x: 10, y: 10 },
      { x: 19, y: 10 },
    ],
    runways: [{ x: 15, y: 15, heading: 4 }],
    airways: [
      { from: { x: 1, y: 1 }, to: { x: 9, y: 9 } },
      { from: { x: 10, y: 1 }, to: { x: 10, y: 9 } },
      { from: { x: 1, y: 10 }, to: { x: 9, y: 10 } },
      { from: { x: 11, y: 10 }, to: { x: 18, y: 10 } },
      { from: { x: 15, y: 11 }, to: { x: 15, y: 14 } },
      { from: { x: 20, y: 10 }, to: { x: 28, y: 10 } },
      { from: { x: 19, y: 11 }, to: { x: 19, y: 19 } },
      { from: { x: 20, y: 11 }, to: { x: 28, y: 19 } },
    ],
    scenery: { seed: 'corner-pockets', coast: 'west', relief: 0.5 },
  },
];
