#!/usr/bin/env node
// Regenerates src/engine/data.js from the upstream sail/globals.c.
//
// The original C source is NOT part of this repository (see root
// ATTRIBUTION.md). Fetch it from https://github.com/vattam/BSDGames
// and pass the path to sail/globals.c:
//
//   node scripts/extract-data.mjs <path-to>/sail/globals.c
//
// Only the *data tables* (scenario list + ship specification rows) are
// transcribed. No C code is copied.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const src = process.argv[2];
if (!src) {
  console.error('usage: node scripts/extract-data.mjs <path-to>/sail/globals.c');
  process.exit(1);
}
const text = readFileSync(src, 'utf8');
const lines = text.split(/\r?\n/);

const NAT = { N_A: 0, N_B: 1, N_S: 2, N_F: 3, N_J: 4, N_D: 5, N_K: 6, N_O: 7 };

// --- scenarios -----------------------------------------------------------
const scenarios = [];
let cur = null;
lines.forEach((line, i) => {
  const head = line.match(/^\s*\{\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(\d+),\s*"([^"]+)",\s*$/);
  if (head) {
    cur = {
      id: scenarios.length,
      winddir: +head[1], windspeed: +head[2], windchange: +head[3],
      name: head[5], line: i + 1, ships: [],
    };
    scenarios.push(cur);
    return;
  }
  const ship = line.match(/^\s*\{\s*"([^"]+)",\s*specs\+(\d+),\s*(N_\w),\s*(-?\d+),\s*(-?\d+),\s*(\d+),\s*0\s*\}/);
  if (ship && cur) {
    cur.ships.push({
      name: ship[1], spec: +ship[2], nationality: NAT[ship[3]],
      row: +ship[4], col: +ship[5], dir: +ship[6],
    });
  }
});
for (const s of scenarios) {
  const decl = lines[s.line - 1].match(/,\s*(\d+),\s*"/);
  if (+decl[1] !== s.ships.length) throw new Error(`vessel count mismatch in ${s.name}`);
}

// --- ship specs ------------------------------------------------------------
const FIELDS = ['bs', 'fs', 'ta', 'guns', 'class', 'hull', 'qual', 'crew1', 'crew2', 'crew3',
  'gunL', 'gunR', 'carL', 'carR', 'rig1', 'rig2', 'rig3', 'rig4', 'pts'];
const specs = [];
lines.forEach((line) => {
  const m = line.match(/^\/\*(\d\d)\*\/\{\s*([-\d,\s]+)\}/);
  if (!m) return;
  const nums = m[2].split(',').map((x) => +x.trim());
  if (nums.length !== FIELDS.length) throw new Error(`bad spec row ${m[1]}`);
  const o = {};
  FIELDS.forEach((f, k) => { o[f] = nums[k]; });
  specs[+m[1]] = o;
});

// --- combat / movement tables ----------------------------------------------
// Each table is a C initializer; we pull every integer inside its braces and
// reshape it to the declared dimensions.
function table(name, dims) {
  const start = lines.findIndex((l) => new RegExp(`\\b${name}\\s*\\[`).test(l) && l.includes('='));
  if (start < 0) throw new Error(`table ${name} not found`);
  let body = '';
  let depth = 0;
  let begun = false;
  for (let i = start; i < lines.length; i++) {
    const l = lines[i].slice(i === start ? lines[i].indexOf('=') : 0);
    for (const ch of l) {
      if (ch === '{') { depth++; begun = true; }
      if (ch === '}') depth--;
    }
    body += l.replace(/\/\*.*?\*\//g, '') + '\n';
    if (begun && depth === 0) break;
  }
  const nums = (body.match(/-?\d+/g) || []).map(Number);
  const total = dims.reduce((a, b) => a * b, 1);
  if (nums.length !== total) throw new Error(`${name}: expected ${total} numbers, got ${nums.length}`);
  const reshape = (arr, ds) => {
    if (ds.length === 1) return arr;
    const size = arr.length / ds[0];
    return Array.from({ length: ds[0] }, (_, k) => reshape(arr.slice(k * size, (k + 1) * size), ds.slice(1)));
  };
  return { value: reshape(nums, dims), line: start + 1 };
}
const TABLES = {
  WET: table('WET', [7, 6, 4]),            // [windspeed][class-1] -> {A,B,C,D}
  RigTable: table('RigTable', [11, 6, 4]), // [hits][roll-1] -> {H,G,C,R}
  HullTable: table('HullTable', [11, 6, 4]),
  AMMO: table('AMMO', [9, 4]),
  HDT: table('HDT', [9, 10]),
  HDTrake: table('HDTrake', [9, 10]),
  QUAL: table('QUAL', [9, 5]),
  MT: table('MT', [9, 3]),
};

const specLine = lines.findIndex((l) => l.includes('struct shipspecs specs[]')) + 1;
const sceneLine = lines.findIndex((l) => l.includes('struct scenario scene[]')) + 1;

const out = `// GENERATED by scripts/extract-data.mjs — do not edit by hand.
//
// Data tables transcribed from the original BSD sail:
//   scenarios  <- sail/globals.c:${sceneLine} (struct scenario scene[])
//   SPECS      <- sail/globals.c:${specLine} (struct shipspecs specs[])
// Upstream: https://github.com/vattam/BSDGames/tree/master/sail
//
// Copyright (c) 1983, 1993 The Regents of the University of California.
// Original game by Dave Riggle; rewrites by Ed Wang and Craig Leres.
//
// Coordinates are the original (row, col) grid; dir is 1..8 (1 = north,
// clockwise). Scenario ids keep the ORIGINAL menu numbering (0-based).

export const SPEC_FIELDS = ${JSON.stringify(FIELDS)};

export const SPECS = [
${specs.map((s, i) => `  /*${String(i).padStart(2, '0')}*/ ${JSON.stringify(s)},`).join('\n')}
];

// Combat / movement tables. Inner quads are [H,G,C,R] for Rig/HullTable and
// [A,B,C,D] for WET, exactly as in the C initializers.
${Object.entries(TABLES).map(([k, t]) => `// ${k} <- sail/globals.c:${t.line}\nexport const ${k} = ${JSON.stringify(t.value)};`).join('\n')}

export const SCENARIOS = [
${scenarios.map((s) => `  {
    id: ${s.id}, name: ${JSON.stringify(s.name)},
    winddir: ${s.winddir}, windspeed: ${s.windspeed}, windchange: ${s.windchange},
    ships: [
${s.ships.map((sh) => `      ${JSON.stringify(sh)},`).join('\n')}
    ],
  },`).join('\n')}
];
`;

const here = dirname(fileURLToPath(import.meta.url));
writeFileSync(join(here, '..', 'src', 'engine', 'data.js'), out);
console.log(`wrote ${scenarios.length} scenarios, ${specs.length} specs`);
