// GENERATED by scripts/extract-data.mjs — do not edit by hand.
//
// Data tables transcribed from the original BSD sail:
//   scenarios  <- sail/globals.c:45 (struct scenario scene[])
//   SPECS      <- sail/globals.c:316 (struct shipspecs specs[])
// Upstream: https://github.com/vattam/BSDGames/tree/master/sail
//
// Copyright (c) 1983, 1993 The Regents of the University of California.
// Original game by Dave Riggle; rewrites by Ed Wang and Craig Leres.
//
// Coordinates are the original (row, col) grid; dir is 1..8 (1 = north,
// clockwise). Scenario ids keep the ORIGINAL menu numbering (0-based).

export const SPEC_FIELDS = ["bs","fs","ta","guns","class","hull","qual","crew1","crew2","crew3","gunL","gunR","carL","carR","rig1","rig2","rig3","rig4","pts"];

export const SPECS = [
  /*00*/ {"bs":4,"fs":7,"ta":3,"guns":19,"class":5,"hull":5,"qual":4,"crew1":2,"crew2":2,"crew3":2,"gunL":2,"gunR":2,"carL":0,"carR":0,"rig1":4,"rig2":4,"rig3":4,"rig4":4,"pts":7},
  /*01*/ {"bs":4,"fs":7,"ta":3,"guns":17,"class":5,"hull":5,"qual":4,"crew1":2,"crew2":2,"crew3":2,"gunL":0,"gunR":0,"carL":4,"carR":4,"rig1":3,"rig2":3,"rig3":3,"rig4":3,"pts":6},
  /*02*/ {"bs":3,"fs":5,"ta":2,"guns":42,"class":4,"hull":7,"qual":4,"crew1":2,"crew2":2,"crew3":2,"gunL":2,"gunR":2,"carL":0,"carR":0,"rig1":5,"rig2":5,"rig3":5,"rig4":-1,"pts":11},
  /*03*/ {"bs":4,"fs":6,"ta":3,"guns":44,"class":3,"hull":7,"qual":4,"crew1":2,"crew2":2,"crew3":2,"gunL":3,"gunR":3,"carL":0,"carR":0,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":12},
  /*04*/ {"bs":3,"fs":5,"ta":2,"guns":64,"class":2,"hull":17,"qual":4,"crew1":8,"crew2":6,"crew3":6,"gunL":12,"gunR":12,"carL":2,"carR":2,"rig1":7,"rig2":7,"rig3":7,"rig4":-1,"pts":20},
  /*05*/ {"bs":3,"fs":5,"ta":2,"guns":74,"class":2,"hull":20,"qual":4,"crew1":8,"crew2":8,"crew3":8,"gunL":16,"gunR":16,"carL":2,"carR":2,"rig1":7,"rig2":7,"rig3":7,"rig4":-1,"pts":26},
  /*06*/ {"bs":3,"fs":5,"ta":2,"guns":50,"class":2,"hull":12,"qual":4,"crew1":6,"crew2":4,"crew3":4,"gunL":8,"gunR":8,"carL":2,"carR":2,"rig1":6,"rig2":6,"rig3":6,"rig4":-1,"pts":17},
  /*07*/ {"bs":3,"fs":5,"ta":1,"guns":98,"class":1,"hull":23,"qual":4,"crew1":10,"crew2":10,"crew3":10,"gunL":18,"gunR":18,"carL":2,"carR":2,"rig1":8,"rig2":8,"rig3":8,"rig4":-1,"pts":28},
  /*08*/ {"bs":3,"fs":5,"ta":2,"guns":74,"class":2,"hull":20,"qual":4,"crew1":8,"crew2":8,"crew3":8,"gunL":16,"gunR":16,"carL":2,"carR":2,"rig1":7,"rig2":7,"rig3":7,"rig4":-1,"pts":26},
  /*09*/ {"bs":3,"fs":5,"ta":2,"guns":74,"class":2,"hull":21,"qual":3,"crew1":10,"crew2":10,"crew3":8,"gunL":20,"gunR":20,"carL":0,"carR":0,"rig1":7,"rig2":7,"rig3":7,"rig4":-1,"pts":24},
  /*10*/ {"bs":3,"fs":5,"ta":1,"guns":80,"class":1,"hull":23,"qual":3,"crew1":12,"crew2":12,"crew3":10,"gunL":22,"gunR":22,"carL":0,"carR":0,"rig1":7,"rig2":7,"rig3":7,"rig4":-1,"pts":27},
  /*11*/ {"bs":3,"fs":5,"ta":2,"guns":64,"class":2,"hull":18,"qual":3,"crew1":8,"crew2":8,"crew3":6,"gunL":12,"gunR":12,"carL":0,"carR":0,"rig1":7,"rig2":7,"rig3":7,"rig4":-1,"pts":18},
  /*12*/ {"bs":3,"fs":5,"ta":2,"guns":44,"class":2,"hull":11,"qual":3,"crew1":4,"crew2":4,"crew3":4,"gunL":6,"gunR":6,"carL":2,"carR":2,"rig1":5,"rig2":5,"rig3":5,"rig4":-1,"pts":10},
  /*13*/ {"bs":3,"fs":5,"ta":2,"guns":50,"class":2,"hull":14,"qual":3,"crew1":6,"crew2":6,"crew3":4,"gunL":8,"gunR":8,"carL":0,"carR":0,"rig1":6,"rig2":6,"rig3":6,"rig4":-1,"pts":14},
  /*14*/ {"bs":4,"fs":6,"ta":3,"guns":36,"class":3,"hull":11,"qual":4,"crew1":4,"crew2":4,"crew3":2,"gunL":4,"gunR":4,"carL":2,"carR":2,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":11},
  /*15*/ {"bs":4,"fs":6,"ta":3,"guns":36,"class":3,"hull":11,"qual":3,"crew1":4,"crew2":4,"crew3":4,"gunL":4,"gunR":4,"carL":2,"carR":2,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":10},
  /*16*/ {"bs":3,"fs":5,"ta":2,"guns":74,"class":2,"hull":21,"qual":4,"crew1":10,"crew2":8,"crew3":8,"gunL":18,"gunR":18,"carL":2,"carR":2,"rig1":7,"rig2":7,"rig3":7,"rig4":-1,"pts":26},
  /*17*/ {"bs":3,"fs":5,"ta":2,"guns":74,"class":2,"hull":21,"qual":3,"crew1":10,"crew2":10,"crew3":8,"gunL":20,"gunR":20,"carL":2,"carR":2,"rig1":7,"rig2":7,"rig3":7,"rig4":-1,"pts":23},
  /*18*/ {"bs":4,"fs":6,"ta":3,"guns":32,"class":3,"hull":8,"qual":3,"crew1":4,"crew2":2,"crew3":2,"gunL":4,"gunR":4,"carL":2,"carR":2,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":9},
  /*19*/ {"bs":4,"fs":6,"ta":3,"guns":24,"class":4,"hull":6,"qual":3,"crew1":4,"crew2":4,"crew3":4,"gunL":2,"gunR":2,"carL":0,"carR":0,"rig1":4,"rig2":4,"rig3":4,"rig4":4,"pts":9},
  /*20*/ {"bs":4,"fs":7,"ta":3,"guns":38,"class":4,"hull":14,"qual":5,"crew1":6,"crew2":4,"crew3":4,"gunL":4,"gunR":4,"carL":6,"carR":6,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":17},
  /*21*/ {"bs":4,"fs":6,"ta":3,"guns":40,"class":3,"hull":15,"qual":3,"crew1":8,"crew2":6,"crew3":6,"gunL":6,"gunR":6,"carL":4,"carR":4,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":15},
  /*22*/ {"bs":4,"fs":7,"ta":3,"guns":36,"class":4,"hull":11,"qual":3,"crew1":6,"crew2":6,"crew3":4,"gunL":4,"gunR":4,"carL":2,"carR":2,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":11},
  /*23*/ {"bs":4,"fs":6,"ta":3,"guns":32,"class":3,"hull":11,"qual":5,"crew1":4,"crew2":4,"crew3":2,"gunL":4,"gunR":4,"carL":2,"carR":2,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":13},
  /*24*/ {"bs":4,"fs":6,"ta":3,"guns":38,"class":3,"hull":14,"qual":5,"crew1":4,"crew2":4,"crew3":4,"gunL":6,"gunR":6,"carL":4,"carR":4,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":18},
  /*25*/ {"bs":4,"fs":6,"ta":3,"guns":22,"class":3,"hull":6,"qual":5,"crew1":2,"crew2":2,"crew3":2,"gunL":0,"gunR":0,"carL":8,"carR":8,"rig1":4,"rig2":4,"rig3":4,"rig4":4,"pts":11},
  /*26*/ {"bs":4,"fs":6,"ta":3,"guns":32,"class":3,"hull":11,"qual":5,"crew1":4,"crew2":4,"crew3":2,"gunL":4,"gunR":4,"carL":2,"carR":2,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":13},
  /*27*/ {"bs":4,"fs":6,"ta":3,"guns":40,"class":3,"hull":14,"qual":3,"crew1":6,"crew2":6,"crew3":4,"gunL":6,"gunR":6,"carL":4,"carR":4,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":15},
  /*28*/ {"bs":4,"fs":6,"ta":3,"guns":32,"class":3,"hull":11,"qual":2,"crew1":4,"crew2":4,"crew3":4,"gunL":4,"gunR":4,"carL":0,"carR":0,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":9},
  /*29*/ {"bs":4,"fs":6,"ta":3,"guns":40,"class":3,"hull":14,"qual":2,"crew1":6,"crew2":6,"crew3":4,"gunL":6,"gunR":6,"carL":4,"carR":4,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":12},
  /*30*/ {"bs":4,"fs":6,"ta":3,"guns":32,"class":3,"hull":8,"qual":2,"crew1":4,"crew2":4,"crew3":1,"gunL":2,"gunR":2,"carL":0,"carR":0,"rig1":4,"rig2":4,"rig3":4,"rig4":4,"pts":7},
  /*31*/ {"bs":4,"fs":7,"ta":3,"guns":44,"class":4,"hull":18,"qual":5,"crew1":6,"crew2":6,"crew3":6,"gunL":8,"gunR":8,"carL":6,"carR":6,"rig1":6,"rig2":6,"rig3":6,"rig4":6,"pts":24},
  /*32*/ {"bs":4,"fs":6,"ta":3,"guns":38,"class":3,"hull":14,"qual":4,"crew1":4,"crew2":4,"crew3":2,"gunL":6,"gunR":6,"carL":4,"carR":4,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":15},
  /*33*/ {"bs":4,"fs":5,"ta":3,"guns":44,"class":3,"hull":18,"qual":5,"crew1":8,"crew2":6,"crew3":6,"gunL":8,"gunR":8,"carL":8,"carR":8,"rig1":6,"rig2":6,"rig3":6,"rig4":6,"pts":24},
  /*34*/ {"bs":4,"fs":6,"ta":3,"guns":38,"class":3,"hull":14,"qual":4,"crew1":4,"crew2":4,"crew3":4,"gunL":6,"gunR":6,"carL":4,"carR":4,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":16},
  /*35*/ {"bs":4,"fs":7,"ta":3,"guns":38,"class":4,"hull":14,"qual":4,"crew1":6,"crew2":6,"crew3":6,"gunL":6,"gunR":6,"carL":6,"carR":6,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":19},
  /*36*/ {"bs":4,"fs":6,"ta":3,"guns":38,"class":3,"hull":14,"qual":3,"crew1":6,"crew2":6,"crew3":4,"gunL":6,"gunR":6,"carL":6,"carR":6,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":14},
  /*37*/ {"bs":4,"fs":6,"ta":3,"guns":38,"class":3,"hull":14,"qual":5,"crew1":6,"crew2":4,"crew3":4,"gunL":6,"gunR":6,"carL":6,"carR":6,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":17},
  /*38*/ {"bs":4,"fs":7,"ta":3,"guns":20,"class":5,"hull":6,"qual":4,"crew1":4,"crew2":2,"crew3":2,"gunL":0,"gunR":0,"carL":6,"carR":6,"rig1":4,"rig2":4,"rig3":4,"rig4":4,"pts":9},
  /*39*/ {"bs":4,"fs":7,"ta":3,"guns":13,"class":6,"hull":3,"qual":4,"crew1":0,"crew2":2,"crew3":2,"gunL":0,"gunR":0,"carL":2,"carR":2,"rig1":2,"rig2":2,"rig3":2,"rig4":2,"pts":5},
  /*40*/ {"bs":4,"fs":7,"ta":3,"guns":19,"class":5,"hull":5,"qual":4,"crew1":2,"crew2":2,"crew3":2,"gunL":2,"gunR":2,"carL":0,"carR":0,"rig1":4,"rig2":4,"rig3":4,"rig4":4,"pts":7},
  /*41*/ {"bs":4,"fs":7,"ta":3,"guns":17,"class":5,"hull":5,"qual":4,"crew1":2,"crew2":2,"crew3":2,"gunL":2,"gunR":2,"carL":0,"carR":0,"rig1":3,"rig2":3,"rig3":3,"rig4":3,"pts":6},
  /*42*/ {"bs":4,"fs":7,"ta":3,"guns":20,"class":5,"hull":6,"qual":5,"crew1":4,"crew2":2,"crew3":2,"gunL":0,"gunR":0,"carL":6,"carR":6,"rig1":4,"rig2":4,"rig3":4,"rig4":4,"pts":12},
  /*43*/ {"bs":4,"fs":7,"ta":3,"guns":18,"class":5,"hull":5,"qual":5,"crew1":2,"crew2":2,"crew3":2,"gunL":0,"gunR":0,"carL":6,"carR":6,"rig1":4,"rig2":4,"rig3":4,"rig4":4,"pts":9},
  /*44*/ {"bs":4,"fs":7,"ta":3,"guns":24,"class":5,"hull":6,"qual":4,"crew1":4,"crew2":2,"crew3":2,"gunL":0,"gunR":0,"carL":10,"carR":10,"rig1":4,"rig2":4,"rig3":4,"rig4":4,"pts":11},
  /*45*/ {"bs":4,"fs":7,"ta":3,"guns":20,"class":5,"hull":6,"qual":4,"crew1":2,"crew2":2,"crew3":2,"gunL":0,"gunR":0,"carL":8,"carR":8,"rig1":4,"rig2":4,"rig3":4,"rig4":4,"pts":10},
  /*46*/ {"bs":4,"fs":6,"ta":3,"guns":44,"class":3,"hull":11,"qual":5,"crew1":4,"crew2":4,"crew3":4,"gunL":4,"gunR":4,"carL":2,"carR":2,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":14},
  /*47*/ {"bs":4,"fs":6,"ta":3,"guns":36,"class":3,"hull":12,"qual":4,"crew1":4,"crew2":4,"crew3":4,"gunL":6,"gunR":6,"carL":2,"carR":2,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":14},
  /*48*/ {"bs":3,"fs":5,"ta":2,"guns":74,"class":2,"hull":21,"qual":3,"crew1":10,"crew2":8,"crew3":8,"gunL":20,"gunR":20,"carL":2,"carR":2,"rig1":4,"rig2":4,"rig3":7,"rig4":-1,"pts":24},
  /*49*/ {"bs":3,"fs":5,"ta":2,"guns":80,"class":2,"hull":24,"qual":4,"crew1":10,"crew2":8,"crew3":8,"gunL":20,"gunR":20,"carL":2,"carR":2,"rig1":8,"rig2":8,"rig3":8,"rig4":-1,"pts":31},
  /*50*/ {"bs":3,"fs":5,"ta":2,"guns":74,"class":2,"hull":21,"qual":4,"crew1":8,"crew2":8,"crew3":6,"gunL":16,"gunR":16,"carL":4,"carR":4,"rig1":7,"rig2":7,"rig3":7,"rig4":-1,"pts":27},
  /*51*/ {"bs":3,"fs":5,"ta":2,"guns":80,"class":2,"hull":24,"qual":3,"crew1":12,"crew2":12,"crew3":10,"gunL":22,"gunR":22,"carL":2,"carR":2,"rig1":7,"rig2":7,"rig3":7,"rig4":-1,"pts":27},
  /*52*/ {"bs":3,"fs":5,"ta":2,"guns":74,"class":2,"hull":21,"qual":3,"crew1":10,"crew2":10,"crew3":8,"gunL":20,"gunR":20,"carL":2,"carR":2,"rig1":7,"rig2":7,"rig3":7,"rig4":-1,"pts":24},
  /*53*/ {"bs":3,"fs":5,"ta":1,"guns":112,"class":1,"hull":27,"qual":2,"crew1":12,"crew2":12,"crew3":12,"gunL":24,"gunR":24,"carL":0,"carR":0,"rig1":9,"rig2":9,"rig3":9,"rig4":-1,"pts":27},
  /*54*/ {"bs":3,"fs":5,"ta":1,"guns":96,"class":1,"hull":24,"qual":2,"crew1":12,"crew2":12,"crew3":10,"gunL":20,"gunR":20,"carL":0,"carR":0,"rig1":8,"rig2":8,"rig3":8,"rig4":-1,"pts":24},
  /*55*/ {"bs":3,"fs":5,"ta":2,"guns":80,"class":2,"hull":23,"qual":2,"crew1":10,"crew2":10,"crew3":8,"gunL":20,"gunR":20,"carL":0,"carR":0,"rig1":7,"rig2":7,"rig3":7,"rig4":-1,"pts":23},
  /*56*/ {"bs":3,"fs":5,"ta":2,"guns":74,"class":2,"hull":21,"qual":2,"crew1":10,"crew2":8,"crew3":8,"gunL":16,"gunR":16,"carL":4,"carR":4,"rig1":7,"rig2":7,"rig3":7,"rig4":-1,"pts":20},
  /*57*/ {"bs":4,"fs":6,"ta":3,"guns":37,"class":3,"hull":12,"qual":4,"crew1":4,"crew2":4,"crew3":2,"gunL":6,"gunR":6,"carL":4,"carR":4,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":14},
  /*58*/ {"bs":4,"fs":7,"ta":3,"guns":16,"class":5,"hull":5,"qual":5,"crew1":2,"crew2":2,"crew3":2,"gunL":0,"gunR":0,"carL":4,"carR":4,"rig1":4,"rig2":4,"rig3":4,"rig4":4,"pts":10},
  /*59*/ {"bs":4,"fs":7,"ta":3,"guns":11,"class":6,"hull":3,"qual":4,"crew1":2,"crew2":2,"crew3":2,"gunL":0,"gunR":0,"carL":2,"carR":2,"rig1":2,"rig2":2,"rig3":2,"rig4":2,"pts":5},
  /*60*/ {"bs":4,"fs":7,"ta":3,"guns":26,"class":5,"hull":6,"qual":4,"crew1":4,"crew2":2,"crew3":2,"gunL":2,"gunR":2,"carL":6,"carR":6,"rig1":4,"rig2":4,"rig3":4,"rig4":4,"pts":12},
  /*61*/ {"bs":4,"fs":7,"ta":3,"guns":20,"class":5,"hull":6,"qual":4,"crew1":4,"crew2":2,"crew3":2,"gunL":0,"gunR":0,"carL":6,"carR":6,"rig1":4,"rig2":4,"rig3":4,"rig4":4,"pts":11},
  /*62*/ {"bs":4,"fs":7,"ta":3,"guns":17,"class":5,"hull":5,"qual":4,"crew1":2,"crew2":2,"crew3":2,"gunL":0,"gunR":0,"carL":6,"carR":6,"rig1":4,"rig2":4,"rig3":4,"rig4":4,"pts":9},
  /*63*/ {"bs":4,"fs":7,"ta":3,"guns":7,"class":6,"hull":3,"qual":4,"crew1":0,"crew2":2,"crew3":2,"gunL":0,"gunR":0,"carL":2,"carR":2,"rig1":2,"rig2":2,"rig3":2,"rig4":2,"pts":4},
  /*64*/ {"bs":4,"fs":6,"ta":3,"guns":40,"class":3,"hull":15,"qual":4,"crew1":4,"crew2":4,"crew3":4,"gunL":8,"gunR":8,"carL":6,"carR":6,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":17},
  /*65*/ {"bs":4,"fs":6,"ta":3,"guns":44,"class":3,"hull":15,"qual":4,"crew1":8,"crew2":8,"crew3":6,"gunL":10,"gunR":10,"carL":2,"carR":2,"rig1":6,"rig2":6,"rig3":6,"rig4":6,"pts":20},
  /*66*/ {"bs":4,"fs":6,"ta":3,"guns":38,"class":3,"hull":14,"qual":4,"crew1":4,"crew2":4,"crew3":4,"gunL":6,"gunR":6,"carL":6,"carR":6,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":15},
  /*67*/ {"bs":4,"fs":5,"ta":3,"guns":44,"class":3,"hull":18,"qual":5,"crew1":8,"crew2":6,"crew3":6,"gunL":8,"gunR":8,"carL":8,"carR":8,"rig1":6,"rig2":6,"rig3":6,"rig4":6,"pts":24},
  /*68*/ {"bs":4,"fs":6,"ta":3,"guns":36,"class":3,"hull":9,"qual":5,"crew1":4,"crew2":4,"crew3":2,"gunL":4,"gunR":4,"carL":2,"carR":2,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":13},
  /*69*/ {"bs":3,"fs":5,"ta":2,"guns":50,"class":2,"hull":14,"qual":2,"crew1":6,"crew2":6,"crew3":6,"gunL":8,"gunR":8,"carL":0,"carR":0,"rig1":6,"rig2":6,"rig3":6,"rig4":-1,"pts":14},
  /*70*/ {"bs":3,"fs":5,"ta":1,"guns":136,"class":1,"hull":30,"qual":1,"crew1":8,"crew2":14,"crew3":14,"gunL":28,"gunR":28,"carL":0,"carR":0,"rig1":9,"rig2":9,"rig3":9,"rig4":-1,"pts":27},
  /*71*/ {"bs":3,"fs":5,"ta":1,"guns":120,"class":1,"hull":27,"qual":5,"crew1":16,"crew2":14,"crew3":14,"gunL":28,"gunR":28,"carL":2,"carR":2,"rig1":9,"rig2":9,"rig3":9,"rig4":-1,"pts":43},
  /*72*/ {"bs":3,"fs":5,"ta":1,"guns":120,"class":2,"hull":21,"qual":5,"crew1":15,"crew2":17,"crew3":15,"gunL":25,"gunR":25,"carL":7,"carR":7,"rig1":9,"rig2":9,"rig3":9,"rig4":-1,"pts":36},
  /*73*/ {"bs":3,"fs":5,"ta":1,"guns":90,"class":3,"hull":18,"qual":4,"crew1":13,"crew2":15,"crew3":13,"gunL":20,"gunR":20,"carL":6,"carR":6,"rig1":5,"rig2":5,"rig3":5,"rig4":5,"pts":28},
  /*74*/ {"bs":4,"fs":7,"ta":3,"guns":6,"class":6,"hull":3,"qual":4,"crew1":2,"crew2":2,"crew3":2,"gunL":20,"gunR":20,"carL":6,"carR":6,"rig1":2,"rig2":2,"rig3":3,"rig4":3,"pts":5},
  /*75*/ {"bs":3,"fs":5,"ta":1,"guns":110,"class":2,"hull":20,"qual":4,"crew1":14,"crew2":15,"crew3":11,"gunL":26,"gunR":26,"carL":8,"carR":8,"rig1":7,"rig2":8,"rig3":9,"rig4":-1,"pts":34},
  /*76*/ {"bs":4,"fs":7,"ta":3,"guns":450,"class":1,"hull":99,"qual":5,"crew1":50,"crew2":40,"crew3":40,"gunL":50,"gunR":50,"carL":25,"carR":25,"rig1":9,"rig2":9,"rig3":9,"rig4":-1,"pts":75},
  /*77*/ {"bs":4,"fs":7,"ta":3,"guns":450,"class":1,"hull":99,"qual":5,"crew1":50,"crew2":40,"crew3":40,"gunL":50,"gunR":50,"carL":25,"carR":25,"rig1":9,"rig2":9,"rig3":9,"rig4":-1,"pts":75},
  /*78*/ {"bs":4,"fs":7,"ta":3,"guns":450,"class":1,"hull":99,"qual":5,"crew1":50,"crew2":40,"crew3":40,"gunL":50,"gunR":50,"carL":25,"carR":25,"rig1":9,"rig2":9,"rig3":9,"rig4":-1,"pts":75},
  /*79*/ {"bs":4,"fs":7,"ta":3,"guns":450,"class":1,"hull":99,"qual":5,"crew1":50,"crew2":40,"crew3":40,"gunL":50,"gunR":50,"carL":25,"carR":25,"rig1":9,"rig2":9,"rig3":9,"rig4":-1,"pts":75},
  /*80*/ {"bs":4,"fs":7,"ta":3,"guns":450,"class":1,"hull":99,"qual":5,"crew1":50,"crew2":40,"crew3":40,"gunL":50,"gunR":50,"carL":25,"carR":25,"rig1":9,"rig2":9,"rig3":9,"rig4":-1,"pts":75},
  /*81*/ {"bs":4,"fs":7,"ta":3,"guns":450,"class":1,"hull":99,"qual":5,"crew1":50,"crew2":40,"crew3":40,"gunL":50,"gunR":50,"carL":25,"carR":25,"rig1":9,"rig2":9,"rig3":9,"rig4":-1,"pts":75},
  /*82*/ {"bs":4,"fs":7,"ta":3,"guns":450,"class":1,"hull":99,"qual":5,"crew1":50,"crew2":40,"crew3":40,"gunL":50,"gunR":50,"carL":25,"carR":25,"rig1":9,"rig2":9,"rig3":9,"rig4":-1,"pts":75},
  /*83*/ {"bs":4,"fs":7,"ta":3,"guns":450,"class":1,"hull":99,"qual":5,"crew1":50,"crew2":40,"crew3":40,"gunL":50,"gunR":50,"carL":25,"carR":25,"rig1":9,"rig2":9,"rig3":9,"rig4":-1,"pts":75},
];

// Combat / movement tables. Inner quads are [H,G,C,R] for Rig/HullTable and
// [A,B,C,D] for WET, exactly as in the C initializers.
// WET <- sail/globals.c:407
export const WET = [[[9,9,9,9],[9,9,9,9],[9,9,9,9],[9,9,9,9],[9,9,9,9],[9,9,9,9]],[[3,2,2,0],[3,2,1,0],[3,2,1,0],[3,2,1,0],[2,1,0,0],[2,1,0,0]],[[1,1,1,0],[1,1,0,0],[1,0,0,0],[1,0,0,0],[1,0,0,0],[1,0,0,0]],[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],[[0,0,0,0],[1,0,0,0],[1,1,0,0],[1,1,0,0],[2,2,1,0],[2,2,1,0]],[[1,0,0,0],[1,1,0,0],[1,1,1,0],[1,1,1,0],[3,2,2,0],[3,2,2,0]],[[2,1,1,0],[3,2,1,0],[3,2,1,0],[3,2,1,0],[3,3,2,0],[3,3,2,0]]];
// RigTable <- sail/globals.c:417
export const RigTable = [[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,1],[0,0,1,0]],[[0,0,0,0],[0,0,0,0],[0,0,0,1],[0,0,1,0],[1,0,0,1],[0,1,1,1]],[[0,0,0,0],[0,0,0,1],[0,0,1,1],[0,1,0,1],[0,1,0,1],[1,0,1,2]],[[0,0,0,0],[0,0,1,1],[0,1,0,1],[0,0,0,2],[0,1,0,2],[1,0,1,2]],[[0,1,0,1],[1,0,0,1],[0,1,1,2],[0,1,0,2],[0,0,1,3],[1,0,1,4]],[[0,0,1,1],[0,1,0,2],[1,0,0,3],[0,1,1,3],[1,0,0,4],[1,1,1,4]],[[0,0,1,2],[0,1,1,2],[1,1,0,3],[0,1,0,4],[1,0,0,4],[1,0,1,5]],[[0,0,1,2],[0,1,0,3],[1,1,0,3],[1,0,2,4],[0,2,1,5],[2,1,0,5]],[[0,2,1,3],[1,0,0,3],[2,1,0,4],[0,1,1,4],[0,1,0,5],[1,0,2,6]],[[1,1,0,4],[1,0,1,4],[2,0,0,5],[0,2,1,5],[0,1,2,6],[0,2,0,7]],[[1,0,1,5],[0,2,0,6],[1,2,0,6],[1,1,1,6],[2,0,2,6],[1,1,2,7]]];
// HullTable <- sail/globals.c:430
export const HullTable = [[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[1,0,0,0],[0,1,0,0]],[[0,0,0,0],[0,0,0,0],[0,1,0,0],[1,1,0,0],[1,0,1,0],[1,0,1,1]],[[0,1,0,0],[1,0,0,0],[1,1,0,0],[1,0,1,0],[1,0,1,1],[2,1,0,0]],[[0,1,1,0],[1,0,0,0],[1,1,1,0],[2,0,0,1],[2,0,1,0],[2,2,0,0]],[[0,1,1,0],[1,0,0,1],[2,1,0,1],[2,2,1,0],[3,0,1,0],[3,1,0,0]],[[1,1,1,0],[2,0,2,1],[2,1,1,0],[2,2,0,0],[3,1,0,1],[3,1,1,0]],[[1,2,2,0],[2,0,2,1],[2,1,0,1],[2,2,0,0],[3,1,1,0],[4,2,1,0]],[[2,1,1,0],[2,0,1,1],[3,2,2,0],[3,2,0,0],[4,2,1,0],[4,2,1,1]],[[2,1,2,0],[3,1,1,1],[3,2,2,0],[4,2,1,0],[4,1,0,2],[4,2,2,0]],[[2,3,1,0],[3,2,2,0],[3,2,2,1],[4,2,2,0],[4,1,0,3],[5,1,2,0]],[[2,2,4,0],[3,3,1,1],[4,2,1,1],[5,1,0,2],[5,1,2,1],[6,2,2,0]]];
// AMMO <- sail/globals.c:444
export const AMMO = [[-1,1,0,1],[-1,1,0,1],[-1,1,0,1],[-2,1,0,2],[-2,2,0,2],[-2,2,0,2],[-3,2,0,2],[-3,2,0,3],[-3,2,0,3]];
// HDT <- sail/globals.c:456
export const HDT = [[1,0,-1,-2,-3,-3,-4,-4,-4,-4],[1,1,0,-1,-2,-2,-3,-3,-3,-3],[2,1,0,-1,-2,-2,-3,-3,-3,-3],[2,2,1,0,-1,-1,-2,-2,-2,-2],[3,2,1,0,-1,-1,-2,-2,-2,-2],[3,3,2,1,0,0,-1,-1,-1,-1],[4,3,2,1,0,0,-1,-1,-1,-1],[4,4,3,2,1,1,0,0,0,0],[5,4,3,2,1,1,0,0,0,0]];
// HDTrake <- sail/globals.c:468
export const HDTrake = [[2,1,0,-1,-2,-2,-3,-3,-3,-3],[2,2,1,0,-1,-1,-2,-2,-2,-2],[3,2,1,0,-1,-1,-2,-2,-2,-2],[4,3,2,1,0,0,-1,-1,-1,-1],[5,4,3,2,1,1,0,0,0,0],[6,5,4,3,2,2,1,1,1,1],[7,6,5,4,3,3,2,2,2,2],[8,7,6,5,4,4,3,3,3,3],[9,8,7,6,5,5,4,4,4,4]];
// QUAL <- sail/globals.c:480
export const QUAL = [[-1,0,0,1,1],[-1,0,0,1,1],[-1,0,0,1,2],[-1,0,0,1,2],[-1,0,0,2,2],[-1,-1,0,2,2],[-2,-1,0,2,2],[-2,-1,0,2,2],[-2,-1,0,2,3]];
// MT <- sail/globals.c:492
export const MT = [[1,0,0],[1,1,0],[2,1,0],[2,1,1],[2,2,1],[3,2,1],[3,2,2],[4,3,2],[4,4,2]];

export const SCENARIOS = [
  {
    id: 0, name: "Ranger vs. Drake",
    winddir: 5, windspeed: 3, windchange: 5,
    ships: [
      {"name":"Ranger","spec":0,"nationality":0,"row":7,"col":20,"dir":4},
      {"name":"Drake","spec":1,"nationality":1,"row":7,"col":31,"dir":5},
    ],
  },
  {
    id: 1, name: "The Battle of Flamborough Head",
    winddir: 1, windspeed: 3, windchange: 6,
    ships: [
      {"name":"Bonhomme Rich","spec":2,"nationality":0,"row":13,"col":40,"dir":2},
      {"name":"Serapis","spec":3,"nationality":1,"row":2,"col":42,"dir":2},
    ],
  },
  {
    id: 2, name: "Arbuthnot and Des Touches",
    winddir: 5, windspeed: 5, windchange: 5,
    ships: [
      {"name":"America","spec":4,"nationality":1,"row":7,"col":37,"dir":4},
      {"name":"Befford","spec":5,"nationality":1,"row":5,"col":35,"dir":4},
      {"name":"Adamant","spec":6,"nationality":1,"row":3,"col":33,"dir":4},
      {"name":"London","spec":7,"nationality":1,"row":1,"col":31,"dir":4},
      {"name":"Royal Oak","spec":8,"nationality":1,"row":-1,"col":29,"dir":4},
      {"name":"Neptune","spec":9,"nationality":3,"row":6,"col":44,"dir":4},
      {"name":"Duc Bougogne","spec":10,"nationality":3,"row":8,"col":46,"dir":4},
      {"name":"Conquerant","spec":48,"nationality":3,"row":10,"col":48,"dir":4},
      {"name":"Provence","spec":11,"nationality":3,"row":12,"col":50,"dir":4},
      {"name":"Romulus","spec":12,"nationality":3,"row":20,"col":58,"dir":4},
    ],
  },
  {
    id: 3, name: "Suffren and Hughes",
    winddir: 1, windspeed: 3, windchange: 5,
    ships: [
      {"name":"Monmouth","spec":52,"nationality":1,"row":9,"col":45,"dir":2},
      {"name":"Hero","spec":5,"nationality":1,"row":13,"col":49,"dir":2},
      {"name":"Isis","spec":6,"nationality":1,"row":12,"col":48,"dir":2},
      {"name":"Superb","spec":50,"nationality":1,"row":10,"col":46,"dir":2},
      {"name":"Burford","spec":48,"nationality":1,"row":11,"col":47,"dir":2},
      {"name":"Flamband","spec":13,"nationality":3,"row":7,"col":59,"dir":4},
      {"name":"Annibal","spec":9,"nationality":3,"row":4,"col":56,"dir":4},
      {"name":"Severe","spec":11,"nationality":3,"row":2,"col":54,"dir":4},
      {"name":"Brilliant","spec":49,"nationality":3,"row":-1,"col":51,"dir":4},
      {"name":"Sphinx","spec":51,"nationality":3,"row":-5,"col":47,"dir":4},
    ],
  },
  {
    id: 4, name: "Nymphe vs. Cleopatre",
    winddir: 1, windspeed: 3, windchange: 4,
    ships: [
      {"name":"Nymphe","spec":14,"nationality":1,"row":13,"col":30,"dir":2},
      {"name":"Cleopatre","spec":15,"nationality":3,"row":3,"col":41,"dir":2},
    ],
  },
  {
    id: 5, name: "Mars vs. Hercule",
    winddir: 1, windspeed: 3, windchange: 5,
    ships: [
      {"name":"Mars","spec":16,"nationality":1,"row":13,"col":30,"dir":2},
      {"name":"Hercule","spec":17,"nationality":3,"row":3,"col":41,"dir":2},
    ],
  },
  {
    id: 6, name: "Ambuscade vs. Baionnaise",
    winddir: 5, windspeed: 3, windchange: 5,
    ships: [
      {"name":"Ambuscade","spec":18,"nationality":1,"row":13,"col":30,"dir":2},
      {"name":"Baionnaise","spec":19,"nationality":3,"row":3,"col":41,"dir":2},
    ],
  },
  {
    id: 7, name: "Constellation vs. Insurgent",
    winddir: 1, windspeed: 5, windchange: 6,
    ships: [
      {"name":"Constellation","spec":20,"nationality":0,"row":9,"col":50,"dir":8},
      {"name":"Insurgent","spec":22,"nationality":3,"row":4,"col":24,"dir":2},
    ],
  },
  {
    id: 8, name: "Constellation vs. Vengeance",
    winddir: 1, windspeed: 3, windchange: 5,
    ships: [
      {"name":"Constellation","spec":20,"nationality":0,"row":12,"col":40,"dir":2},
      {"name":"Vengeance","spec":21,"nationality":3,"row":1,"col":43,"dir":2},
    ],
  },
  {
    id: 9, name: "The Battle of Lissa",
    winddir: 1, windspeed: 3, windchange: 6,
    ships: [
      {"name":"Amphion","spec":23,"nationality":1,"row":8,"col":50,"dir":4},
      {"name":"Active","spec":24,"nationality":1,"row":6,"col":48,"dir":4},
      {"name":"Volage","spec":25,"nationality":1,"row":4,"col":46,"dir":4},
      {"name":"Cerberus","spec":26,"nationality":1,"row":2,"col":44,"dir":4},
      {"name":"Favorite","spec":27,"nationality":3,"row":9,"col":34,"dir":2},
      {"name":"Flore","spec":21,"nationality":3,"row":13,"col":39,"dir":2},
      {"name":"Danae","spec":64,"nationality":3,"row":15,"col":37,"dir":2},
      {"name":"Bellona","spec":28,"nationality":3,"row":17,"col":35,"dir":2},
      {"name":"Corona","spec":29,"nationality":3,"row":12,"col":31,"dir":2},
      {"name":"Carolina","spec":30,"nationality":3,"row":15,"col":28,"dir":2},
    ],
  },
  {
    id: 10, name: "Constitution vs. Guerriere",
    winddir: 2, windspeed: 5, windchange: 6,
    ships: [
      {"name":"Constitution","spec":31,"nationality":0,"row":7,"col":35,"dir":1},
      {"name":"Guerriere","spec":32,"nationality":1,"row":7,"col":47,"dir":4},
    ],
  },
  {
    id: 11, name: "United States vs. Macedonian",
    winddir: 1, windspeed: 3, windchange: 5,
    ships: [
      {"name":"United States","spec":33,"nationality":0,"row":1,"col":52,"dir":6},
      {"name":"Macedonian","spec":34,"nationality":1,"row":14,"col":40,"dir":1},
    ],
  },
  {
    id: 12, name: "Constitution vs. Java",
    winddir: 1, windspeed: 3, windchange: 6,
    ships: [
      {"name":"Constitution","spec":31,"nationality":0,"row":1,"col":40,"dir":2},
      {"name":"Java","spec":35,"nationality":1,"row":11,"col":40,"dir":2},
    ],
  },
  {
    id: 13, name: "Chesapeake vs. Shannon",
    winddir: 1, windspeed: 3, windchange: 5,
    ships: [
      {"name":"Chesapeake","spec":36,"nationality":0,"row":13,"col":40,"dir":2},
      {"name":"Shannon","spec":37,"nationality":1,"row":1,"col":42,"dir":2},
    ],
  },
  {
    id: 14, name: "The Battle of Lake Erie",
    winddir: 1, windspeed: 1, windchange: 6,
    ships: [
      {"name":"Lawrence","spec":38,"nationality":0,"row":4,"col":55,"dir":8},
      {"name":"Niagara","spec":42,"nationality":0,"row":7,"col":61,"dir":8},
      {"name":"Lady Prevost","spec":39,"nationality":1,"row":4,"col":25,"dir":2},
      {"name":"Detroit","spec":40,"nationality":1,"row":7,"col":22,"dir":2},
      {"name":"Q. Charlotte","spec":41,"nationality":1,"row":10,"col":19,"dir":2},
    ],
  },
  {
    id: 15, name: "Wasp vs. Reindeer",
    winddir: 1, windspeed: 1, windchange: 5,
    ships: [
      {"name":"Wasp","spec":42,"nationality":0,"row":3,"col":41,"dir":2},
      {"name":"Reindeer","spec":43,"nationality":1,"row":10,"col":48,"dir":2},
    ],
  },
  {
    id: 16, name: "Constitution vs. Cyane and Levant",
    winddir: 1, windspeed: 2, windchange: 5,
    ships: [
      {"name":"Constitution","spec":31,"nationality":0,"row":10,"col":45,"dir":2},
      {"name":"Cyane","spec":44,"nationality":1,"row":3,"col":37,"dir":2},
      {"name":"Levant","spec":45,"nationality":1,"row":5,"col":35,"dir":2},
    ],
  },
  {
    id: 17, name: "Pellew vs. Droits de L'Homme",
    winddir: 5, windspeed: 5, windchange: 5,
    ships: [
      {"name":"Indefatigable","spec":46,"nationality":1,"row":12,"col":45,"dir":6},
      {"name":"Amazon","spec":47,"nationality":1,"row":9,"col":48,"dir":6},
      {"name":"Droits L'Hom","spec":48,"nationality":3,"row":3,"col":28,"dir":5},
    ],
  },
  {
    id: 18, name: "Algeciras",
    winddir: 2, windspeed: 2, windchange: 3,
    ships: [
      {"name":"Caesar","spec":49,"nationality":1,"row":7,"col":70,"dir":6},
      {"name":"Pompee","spec":50,"nationality":1,"row":5,"col":72,"dir":6},
      {"name":"Spencer","spec":5,"nationality":1,"row":3,"col":74,"dir":6},
      {"name":"Hannibal","spec":7,"nationality":1,"row":1,"col":76,"dir":6},
      {"name":"Real-Carlos","spec":53,"nationality":2,"row":9,"col":20,"dir":3},
      {"name":"San Fernando","spec":54,"nationality":2,"row":11,"col":16,"dir":3},
      {"name":"Argonauta","spec":55,"nationality":2,"row":10,"col":14,"dir":4},
      {"name":"San Augustine","spec":56,"nationality":2,"row":6,"col":22,"dir":4},
      {"name":"Indomptable","spec":51,"nationality":3,"row":7,"col":23,"dir":5},
      {"name":"Desaix","spec":52,"nationality":3,"row":7,"col":27,"dir":7},
    ],
  },
  {
    id: 19, name: "Lake Champlain",
    winddir: 5, windspeed: 3, windchange: 6,
    ships: [
      {"name":"Saratoga","spec":60,"nationality":0,"row":8,"col":10,"dir":1},
      {"name":"Eagle","spec":61,"nationality":0,"row":9,"col":13,"dir":2},
      {"name":"Ticonderoga","spec":62,"nationality":0,"row":12,"col":17,"dir":3},
      {"name":"Preble","spec":63,"nationality":0,"row":14,"col":20,"dir":2},
      {"name":"Confiance","spec":57,"nationality":1,"row":4,"col":70,"dir":6},
      {"name":"Linnet","spec":58,"nationality":1,"row":7,"col":68,"dir":6},
      {"name":"Chubb","spec":59,"nationality":1,"row":10,"col":65,"dir":6},
    ],
  },
  {
    id: 20, name: "Last Voyage of the USS President",
    winddir: 5, windspeed: 3, windchange: 6,
    ships: [
      {"name":"President","spec":67,"nationality":0,"row":12,"col":42,"dir":5},
      {"name":"Endymion","spec":64,"nationality":1,"row":5,"col":42,"dir":5},
      {"name":"Pomone","spec":65,"nationality":1,"row":7,"col":82,"dir":6},
      {"name":"Tenedos","spec":66,"nationality":1,"row":7,"col":-1,"dir":4},
    ],
  },
  {
    id: 21, name: "Hornblower and the Natividad",
    winddir: 7, windspeed: 5, windchange: 5,
    ships: [
      {"name":"Lydia","spec":68,"nationality":1,"row":12,"col":40,"dir":2},
      {"name":"Natividad","spec":69,"nationality":2,"row":2,"col":40,"dir":4},
    ],
  },
  {
    id: 22, name: "Curse of the Flying Dutchman",
    winddir: 1, windspeed: 3, windchange: 6,
    ships: [
      {"name":"Piece of Cake","spec":19,"nationality":2,"row":7,"col":40,"dir":2},
      {"name":"Flying Dutchy","spec":71,"nationality":3,"row":7,"col":41,"dir":1},
    ],
  },
  {
    id: 23, name: "The South Pacific",
    winddir: 1, windspeed: 4, windchange: 1,
    ships: [
      {"name":"USS Scurvy","spec":70,"nationality":0,"row":7,"col":40,"dir":1},
      {"name":"HMS Tahiti","spec":71,"nationality":1,"row":12,"col":60,"dir":1},
      {"name":"Australian","spec":18,"nationality":2,"row":5,"col":20,"dir":8},
      {"name":"Bikini Atoll","spec":63,"nationality":3,"row":2,"col":60,"dir":4},
    ],
  },
  {
    id: 24, name: "Hornblower and the battle of Rosas bay",
    winddir: 7, windspeed: 3, windchange: 6,
    ships: [
      {"name":"Sutherland","spec":5,"nationality":1,"row":13,"col":30,"dir":2},
      {"name":"Turenne","spec":10,"nationality":3,"row":9,"col":35,"dir":6},
      {"name":"Nightmare","spec":9,"nationality":3,"row":7,"col":37,"dir":6},
      {"name":"Paris","spec":53,"nationality":3,"row":3,"col":45,"dir":4},
      {"name":"Napoleon","spec":56,"nationality":3,"row":1,"col":40,"dir":6},
    ],
  },
  {
    id: 25, name: "Cape Horn",
    winddir: 6, windspeed: 4, windchange: 7,
    ships: [
      {"name":"Concord","spec":51,"nationality":0,"row":3,"col":20,"dir":4},
      {"name":"Berkeley","spec":7,"nationality":0,"row":5,"col":50,"dir":5},
      {"name":"Thames","spec":71,"nationality":1,"row":10,"col":40,"dir":1},
      {"name":"Madrid","spec":53,"nationality":2,"row":13,"col":60,"dir":8},
      {"name":"Musket","spec":10,"nationality":3,"row":10,"col":60,"dir":7},
    ],
  },
  {
    id: 26, name: "New Orleans",
    winddir: 8, windspeed: 3, windchange: 7,
    ships: [
      {"name":"Alligator","spec":71,"nationality":0,"row":13,"col":5,"dir":1},
      {"name":"Firefly","spec":50,"nationality":1,"row":10,"col":20,"dir":8},
      {"name":"Cypress","spec":46,"nationality":1,"row":5,"col":10,"dir":6},
    ],
  },
  {
    id: 27, name: "Botany Bay",
    winddir: 5, windspeed: 3, windchange: 7,
    ships: [
      {"name":"Shark","spec":11,"nationality":1,"row":6,"col":15,"dir":4},
      {"name":"Coral Snake","spec":31,"nationality":3,"row":3,"col":30,"dir":6},
      {"name":"Sea Lion","spec":33,"nationality":3,"row":13,"col":50,"dir":8},
    ],
  },
  {
    id: 28, name: "Voyage to the Bottom of the Sea",
    winddir: 4, windspeed: 3, windchange: 6,
    ships: [
      {"name":"Seaview","spec":71,"nationality":0,"row":6,"col":3,"dir":3},
      {"name":"Flying Sub","spec":64,"nationality":0,"row":8,"col":3,"dir":3},
      {"name":"Mermaid","spec":70,"nationality":1,"row":2,"col":5,"dir":5},
      {"name":"Giant Squid","spec":53,"nationality":2,"row":10,"col":30,"dir":8},
    ],
  },
  {
    id: 29, name: "Frigate Action",
    winddir: 7, windspeed: 3, windchange: 6,
    ships: [
      {"name":"Killdeer","spec":21,"nationality":0,"row":7,"col":20,"dir":8},
      {"name":"Sandpiper","spec":27,"nationality":1,"row":5,"col":40,"dir":8},
      {"name":"Curlew","spec":34,"nationality":2,"row":10,"col":60,"dir":8},
    ],
  },
  {
    id: 30, name: "The Battle of Midway",
    winddir: 7, windspeed: 2, windchange: 5,
    ships: [
      {"name":"Enterprise","spec":49,"nationality":0,"row":10,"col":70,"dir":8},
      {"name":"Yorktown","spec":51,"nationality":0,"row":3,"col":70,"dir":7},
      {"name":"Hornet","spec":52,"nationality":0,"row":6,"col":70,"dir":7},
      {"name":"Akagi","spec":53,"nationality":4,"row":6,"col":10,"dir":4},
      {"name":"Kaga","spec":54,"nationality":4,"row":4,"col":12,"dir":4},
      {"name":"Soryu","spec":55,"nationality":4,"row":2,"col":14,"dir":4},
    ],
  },
  {
    id: 31, name: "Star Trek",
    winddir: 1, windspeed: 3, windchange: 4,
    ships: [
      {"name":"Enterprise","spec":76,"nationality":5,"row":-10,"col":60,"dir":7},
      {"name":"Yorktown","spec":77,"nationality":5,"row":0,"col":70,"dir":7},
      {"name":"Reliant","spec":78,"nationality":5,"row":10,"col":70,"dir":7},
      {"name":"Galileo","spec":79,"nationality":5,"row":20,"col":60,"dir":7},
      {"name":"Kobayashi Maru","spec":80,"nationality":6,"row":0,"col":120,"dir":7},
      {"name":"Klingon II","spec":81,"nationality":6,"row":10,"col":120,"dir":7},
      {"name":"Red Orion","spec":82,"nationality":7,"row":0,"col":0,"dir":3},
      {"name":"Blue Orion","spec":83,"nationality":7,"row":10,"col":0,"dir":3},
    ],
  },
];
