#!/usr/bin/env node
// Computes 2D map coordinates for the 275 rooms (minimap + world map) and
// writes src/scene/layout.js. Deterministic: a breadth-first placement on a
// grid followed by spring relaxation over the real N/S/E/W links (up/down
// as short diagonals), with repulsion so rooms do not overlap.
//
//   node scripts/make-layout.mjs

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { DAYFILE, NIGHTFILE } from '../src/engine/data/world.js';
import { ROOM_CLASS } from '../src/scene/composer.js';

const here = dirname(fileURLToPath(import.meta.url));
const N = 275;

const layerOf = (n) => {
  const b = ROOM_CLASS[n].biome;
  if (b === 'ship') return 'ship';
  if (b === 'space') return 'space';
  if (b === 'air') return 'air';
  if (b === 'cave') return 'caves';
  return 'island';
};

// direction vectors: north up (y-), south down, east right, west left.
const DIR = [[0, -1], [0, 1], [1, 0], [-1, 0]];
const UP = [0.45, -0.55];
const DOWN = [-0.45, 0.55];

const layers = {};
for (let n = 1; n <= N; n++) (layers[layerOf(n)] ||= []).push(n);

const pos = new Array(N + 1);
for (const [name, rooms] of Object.entries(layers)) {
  const inLayer = new Set(rooms);
  const edges = [];
  for (const F of [DAYFILE, NIGHTFILE]) {
    for (const u of rooms) {
      const l = F[u].link;
      for (let i = 0; i < 4; i++) if (l[i] && l[i] !== u && inLayer.has(l[i])) edges.push([u, l[i], DIR[i]]);
      if (l[4] && l[4] !== u && inLayer.has(l[4])) edges.push([u, l[4], UP]);
      if (l[6] && l[6] !== u && inLayer.has(l[6])) edges.push([u, l[6], DOWN]);
    }
  }
  // BFS placement from the lowest-numbered room of each component.
  const p = new Map();
  const occupied = new Set();
  const key = (x, y) => `${Math.round(x * 4)},${Math.round(y * 4)}`;
  let compX = 0;
  for (const root of rooms) {
    if (p.has(root)) continue;
    const q = [root];
    p.set(root, [compX, 0]);
    occupied.add(key(compX, 0));
    let maxX = compX;
    while (q.length) {
      const u = q.shift();
      for (const [a, b, d] of edges) {
        if (a !== u || p.has(b)) continue;
        let [x, y] = p.get(u);
        x += d[0]; y += d[1];
        let tries = 0;
        while (occupied.has(key(x, y)) && tries++ < 12) { x += 0.5 * d[1] || 0.5; y += 0.5 * d[0] || 0.5; }
        p.set(b, [x, y]);
        occupied.add(key(x, y));
        maxX = Math.max(maxX, x);
        q.push(b);
      }
    }
    compX = maxX + 3;
  }
  // Relaxation.
  const ids = rooms;
  for (let it = 0; it < 1500; it++) {
    const k = 0.12 * (1 - it / 1600);
    for (const [a, b, d] of edges) {
      const pa = p.get(a);
      const pb = p.get(b);
      const ex = (pb[0] - pa[0]) - d[0];
      const ey = (pb[1] - pa[1]) - d[1];
      pa[0] += 0.5 * k * ex; pa[1] += 0.5 * k * ey;
      pb[0] -= 0.5 * k * ex; pb[1] -= 0.5 * k * ey;
    }
    for (let i = 0; i < ids.length; i++) {
      const pi = p.get(ids[i]);
      for (let j = i + 1; j < ids.length; j++) {
        const pj = p.get(ids[j]);
        const dx = pj[0] - pi[0];
        const dy = pj[1] - pi[1];
        const d2 = dx * dx + dy * dy;
        if (d2 < 0.64) {
          const d = Math.sqrt(d2) || 0.01;
          const push = (0.8 - d) * 0.25;
          const ux = d2 ? dx / d : ((ids[i] * 13) % 7) / 7 - 0.5;
          const uy = d2 ? dy / d : ((ids[j] * 7) % 5) / 5 - 0.5;
          pi[0] -= ux * push; pi[1] -= uy * push;
          pj[0] += ux * push; pj[1] += uy * push;
        }
      }
    }
  }
  // Normalise to [0,1] keeping aspect.
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  for (const n of rooms) { const [x, y] = p.get(n); x0 = Math.min(x0, x); y0 = Math.min(y0, y); x1 = Math.max(x1, x); y1 = Math.max(y1, y); }
  const s = Math.max(x1 - x0, y1 - y0) || 1;
  for (const n of rooms) {
    const [x, y] = p.get(n);
    pos[n] = [+((x - x0) / s).toFixed(4), +((y - y0) / s).toFixed(4), name, +((x1 - x0) / s).toFixed(4), +((y1 - y0) / s).toFixed(4)];
  }
}

const out = `// GENERATED by scripts/make-layout.mjs -- do not edit by hand.
// Map coordinates for every room: [x, y, layer, layerWidth, layerHeight],
// x and y in 0..1 of the layer's larger side (north is up).
export const LAYOUT = ${JSON.stringify(pos)};
export const LAYERS = ${JSON.stringify(Object.keys(layers))};
`;
writeFileSync(join(here, '../src/scene/layout.js'), out);
console.log('layout written:', Object.fromEntries(Object.entries(layers).map(([k, v]) => [k, v.length])));
