/**
 * `pnpm run docs`: regenerates the games table in README.md from the catalog, between the
 * `<!-- games:start -->` and `<!-- games:end -->` markers. `--check` only reports staleness (CI).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { GameManifest } from '../packages/kit/src/manifest/manifest';
import { readCatalog } from './lib/catalog';
import { isMainModule, REPO_ROOT } from './lib/paths';
import { green, red } from './lib/report';

/** Prettier aligns Markdown tables; formatting the table the same way keeps --check stable. */
export async function formatTable(table: string): Promise<string> {
  const prettier = await import('prettier');
  const options = (await prettier.resolveConfig(join(REPO_ROOT, 'README.md'))) ?? {};
  return (await prettier.format(table, { ...options, parser: 'markdown' })).trim();
}

export const START_MARKER = '<!-- games:start -->';
export const END_MARKER = '<!-- games:end -->';

const STATUS_WORDS: Record<GameManifest['status'], string> = {
  'coming-soon': 'coming soon',
  adopting: 'adopting',
  shipped: 'shipped',
  unlisted: 'unlisted',
};

function cell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

export function gamesTable(manifests: readonly GameManifest[]): string {
  const rows = manifests
    .filter((manifest) => manifest.status !== 'unlisted')
    .map(
      (m) =>
        `| ${cell(m.title)} | \`${m.directory}\` | ${cell(`${m.inspiredBy.uiTitle} (${m.inspiredBy.year})`)} | ${STATUS_WORDS[m.status]} | ${m.kind} |`,
    );
  return [
    '| Game | Directory | Inspired by | Status | Kind |',
    '|---|---|---|---|---|',
    ...rows,
  ].join('\n');
}

/** Returns the README with the table replaced, or null when the markers are missing. */
export function replaceTable(readme: string, table: string): string | null {
  const start = readme.indexOf(START_MARKER);
  const end = readme.indexOf(END_MARKER);
  if (start < 0 || end < start) return null;
  const note = '<!-- Generated by `pnpm run docs` from the Hall catalog. Do not edit by hand. -->';
  return `${readme.slice(0, start + START_MARKER.length)}\n\n${note}\n\n${table}\n\n${readme.slice(end)}`;
}

async function main(checkOnly: boolean): Promise<number> {
  const readmePath = join(REPO_ROOT, 'README.md');
  if (!existsSync(readmePath)) {
    console.error(red('README.md is missing; nothing to update.'));
    return 1;
  }
  const catalog = readCatalog();
  const broken = catalog.games.filter((entry) => !entry.manifest);
  if (broken.length > 0) {
    console.error(
      red(
        `Catalog has invalid entries (${broken.map((e) => e.id).join(', ')}); run pnpm check:catalog.`,
      ),
    );
    return 1;
  }
  const readme = readFileSync(readmePath, 'utf8');
  const table = await formatTable(
    gamesTable(catalog.games.map((entry) => entry.manifest as GameManifest)),
  );
  const next = replaceTable(readme, table);
  if (next === null) {
    console.error(red(`README.md needs the ${START_MARKER} and ${END_MARKER} markers.`));
    return 1;
  }
  if (checkOnly) {
    if (next === readme) {
      console.log(green('✓ README games table is up to date'));
      return 0;
    }
    console.error(red('✗ README games table is stale; run pnpm run docs'));
    return 1;
  }
  if (next !== readme) writeFileSync(readmePath, next);
  console.log(
    green(
      next === readme
        ? '✓ README games table already up to date'
        : '✓ README games table regenerated',
    ),
  );
  return 0;
}

if (isMainModule(import.meta.url)) process.exitCode = await main(process.argv.includes('--check'));
