import type { PuzzleSpec } from './puzzles';

/** Written by `scripts/puzzles.ts`; checked by `puzzles.test.ts`. Do not edit by hand. */
export const PUZZLE_DATA: readonly PuzzleSpec[] = [
  { columns: 3, rows: 3, lines: 'fff30f', owners: 'y.....rrr', target: 3, kind: 'decline' },
  { columns: 3, rows: 3, lines: 'f3afb6', owners: 'yrr......', target: 4, kind: 'decline' },
  { columns: 3, rows: 3, lines: 'd64ffd', owners: 'r.yy.....', target: 4, kind: 'decline' },
  { columns: 3, rows: 3, lines: 'b1ffb2', owners: 'yy.......', target: 5, kind: 'decline' },
  { columns: 3, rows: 3, lines: 'be2bbd', owners: 'y..y.....', target: 5, kind: 'decline' },
  { columns: 3, rows: 3, lines: '76ade7', owners: '..y...r..', target: 5, kind: 'decline' },
  { columns: 3, rows: 3, lines: 'de2fbc', owners: 'y.ry.....', target: 4, kind: 'choice' },
  { columns: 3, rows: 3, lines: 'ec35bb', owners: '...y..y..', target: 5, kind: 'choice' },
  { columns: 3, rows: 3, lines: '32ea7a', owners: '.........', target: 3, kind: 'choice' },
  { columns: 3, rows: 3, lines: 'c1e5aa', owners: '.........', target: 6, kind: 'choice' },
  { columns: 3, rows: 3, lines: '6488d6', owners: '.........', target: 2, kind: 'sacrifice' },
  { columns: 3, rows: 3, lines: '46806a', owners: '.........', target: 3, kind: 'sacrifice' },
  { columns: 4, rows: 3, lines: 'f32e7ff5', owners: 'rr...y...y..', target: 6, kind: 'decline' },
  { columns: 4, rows: 3, lines: 'bb07fbb6', owners: 'rr.y........', target: 7, kind: 'decline' },
  { columns: 4, rows: 3, lines: '554ffd73', owners: 'r.y...y...y.', target: 3, kind: 'choice' },
  { columns: 4, rows: 3, lines: 'b8e8d7f6', owners: '...r...y...y', target: 7, kind: 'choice' },
  { columns: 4, rows: 3, lines: 'ebc39575', owners: '...y...r....', target: 8, kind: 'choice' },
  { columns: 4, rows: 3, lines: '12dbdbe6', owners: '........r..y', target: 3, kind: 'choice' },
  { columns: 4, rows: 3, lines: '9837eb36', owners: '...y........', target: 7, kind: 'decline' },
  { columns: 4, rows: 3, lines: '883efb72', owners: '...y........', target: 7, kind: 'decline' },
  { columns: 4, rows: 3, lines: '83cadae6', owners: '...........y', target: 6, kind: 'choice' },
  { columns: 4, rows: 3, lines: 'bc6f4620', owners: '............', target: 9, kind: 'sacrifice' },
  { columns: 4, rows: 3, lines: '25a39554', owners: '............', target: 5, kind: 'sacrifice' },
  { columns: 4, rows: 3, lines: '9b0448c6', owners: '............', target: 5, kind: 'sacrifice' },
  {
    columns: 4,
    rows: 4,
    lines: 'b79bb7b6ff',
    owners: 'yy.........rrr.r',
    target: 6,
    kind: 'decline',
  },
  {
    columns: 4,
    rows: 4,
    lines: 'ef929e17f6',
    owners: '.yyy...y........',
    target: 9,
    kind: 'decline',
  },
  {
    columns: 4,
    rows: 4,
    lines: '5f52537e6d',
    owners: 'r...y...........',
    target: 9,
    kind: 'decline',
  },
  {
    columns: 4,
    rows: 4,
    lines: 'fcf11d30df',
    owners: '..yy........r...',
    target: 7,
    kind: 'choice',
  },
  {
    columns: 4,
    rows: 4,
    lines: 'fa50f9bada',
    owners: '...y............',
    target: 2,
    kind: 'choice',
  },
  {
    columns: 4,
    rows: 4,
    lines: 'c36f6537c8',
    owners: '................',
    target: 10,
    kind: 'choice',
  },
  {
    columns: 4,
    rows: 4,
    lines: 'd213e2b3f4',
    owners: '................',
    target: 12,
    kind: 'choice',
  },
  {
    columns: 4,
    rows: 4,
    lines: 'f720a017f5',
    owners: '................',
    target: 9,
    kind: 'sacrifice',
  },
  {
    columns: 4,
    rows: 4,
    lines: '5636d23721',
    owners: '................',
    target: 9,
    kind: 'sacrifice',
  },
  {
    columns: 4,
    rows: 4,
    lines: '65e4915243',
    owners: '................',
    target: 9,
    kind: 'sacrifice',
  },
  {
    columns: 5,
    rows: 4,
    lines: 'f708fffae5d70',
    owners: 'yy.............rry..',
    target: 13,
    kind: 'decline',
  },
  {
    columns: 5,
    rows: 4,
    lines: '7319c67dbdaa1',
    owners: 'y..................r',
    target: 13,
    kind: 'decline',
  },
  {
    columns: 5,
    rows: 4,
    lines: 'd566bf596ae81',
    owners: '..............y....y',
    target: 3,
    kind: 'choice',
  },
  {
    columns: 5,
    rows: 4,
    lines: '7a3a1f1235641',
    owners: '....................',
    target: 11,
    kind: 'choice',
  },
  {
    columns: 5,
    rows: 4,
    lines: '9fa1620907e51',
    owners: '....................',
    target: 12,
    kind: 'sacrifice',
  },
  {
    columns: 5,
    rows: 4,
    lines: '1c392b3d15641',
    owners: '....................',
    target: 10,
    kind: 'sacrifice',
  },
];
